'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'ar' | 'bn' | 'id' | 'uz' | 'ru' | 'fr' | 'kk' | 'ms'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.properties': 'Properties',
    'nav.services': 'Services',
    'nav.login': 'Login',
    'nav.getStarted': 'Get Started',
    'nav.dashboard': 'Dashboard',
    'nav.settings': 'Settings',
    'nav.createPost': 'Create Post',
    'nav.logout': 'Logout',

    // Hero Section
    'hero.title': 'Student Housing in Egypt',
    'hero.subtitle': 'Trusted listings for international students',
    'hero.location': 'Location',
    'hero.propertyType': 'Property Type',
    'hero.priceRange': 'Price Range',
    'hero.search': 'Search',
    'hero.apartment': 'Apartment',
    'hero.room': 'Room',
    'hero.roommate': 'Roommate',

    // Stats
    'stats.properties': 'Properties',
    'stats.students': 'Students',
    'stats.agents': 'Agents',
    'stats.satisfied': 'Satisfied Clients',

    // Properties Section
    'properties.featured': 'Featured Properties',
    'properties.viewAll': 'View All',
    'properties.bedrooms': 'Bedrooms',
    'properties.bathrooms': 'Bathrooms',
    'properties.area': 'Area',
    'properties.month': 'month',

    // Properties Page
    'propertiesPage.title': 'Browse Properties',
    'propertiesPage.subtitle': 'Find your perfect home in Egypt',
    'propertiesPage.filters': 'Filters',
    'propertiesPage.city': 'Location',
    'propertiesPage.type': 'Type',
    'propertiesPage.price': 'Price (EGP)',
    'propertiesPage.minPrice': 'Min Price',
    'propertiesPage.maxPrice': 'Max Price',
    'propertiesPage.clearFilters': 'Clear Filters',
    'propertiesPage.found': 'Found',
    'propertiesPage.noProperties': 'No properties found',
    'propertiesPage.adjustFilters': 'Try adjusting your filters',
    'propertiesPage.viewDetails': 'View Details',
    'propertiesPage.whatsapp': 'WhatsApp',
    'propertiesPage.views': 'views',
    'propertiesPage.likes': 'likes',
    'propertiesPage.loading': 'Loading properties...',
    'propertiesPage.allAreas': 'All Areas',
    'propertiesPage.cairoAll': 'Cairo (All)',
    'propertiesPage.allTypes': 'All Types',
    'propertiesPage.propertyType': 'Property',
    'propertiesPage.roomType': 'Room',
    'propertiesPage.roommateType': 'Roommate',
    'propertiesPage.any': 'Any',
    'propertiesPage.reset': 'Reset',
    'propertiesPage.apply': 'Apply',
    'propertiesPage.addProperty': 'Add Property',
    'propertiesPage.notAvailable': 'Not Available',
    'propertiesPage.restore': 'Restore',
    'propertiesPage.br': 'BR',
    'propertiesPage.ba': 'BA',
    'propertiesPage.more': 'more',

    // Property Detail Page
    'detail.backToProperties': 'Back to Properties',
    'detail.home': 'Home',
    'detail.properties': 'Properties',
    'detail.share': 'Share',
    'detail.monthlyRent': 'Monthly Rent',
    'detail.propertyDetails': 'Property Details',
    'detail.description': 'Description',
    'detail.amenities': 'Amenities & Features',
    'detail.preferences': 'Preferences',
    'detail.videos': 'Property Videos',
    'detail.postedBy': 'Posted By',
    'detail.yourProperty': 'Your Property',
    'detail.manageProperty': 'Manage your listing',
    'detail.editProperty': 'Edit Property',
    'detail.deleteProperty': 'Delete Property',
    'detail.deleting': 'Deleting...',
    'detail.contactWhatsapp': 'Contact via WhatsApp',
    'detail.directMessage': 'Direct message to the property owner',
    'detail.safetyTips': 'Safety Tips',
    'detail.safetyTip1': 'Always visit the property in person before making payments',
    'detail.safetyTip2': 'Never transfer money without seeing the property first',
    'detail.safetyTip3': 'Verify the identity of the property owner',
    'detail.notFound': 'Property not found',
    'detail.notFoundDesc': 'This listing may have been removed or is no longer available.',
    'detail.forFamily': 'For Family',
    'detail.forStudents': 'For Students',
    'detail.furnished': 'Furnished',
    'detail.type': 'Type',
    'detail.memberSince': 'Member since',
    'detail.viewAllPhotos': 'View all photos',

    // Services
    'services.title': 'Home Services',
    'services.viewProviders': 'View Providers',

    // Services Page
    'servicesPage.heroTitle': 'Home Services at Your Doorstep',
    'servicesPage.heroSubtitle': 'Find trusted professionals for plumbing, electrical, cleaning, AC repair, painting, and carpentry services across Cairo.',
    'servicesPage.searchPlaceholder': 'Search for a service...',
    'servicesPage.providers': 'Service Providers',
    'servicesPage.categories': 'Service Categories',
    'servicesPage.avgRating': 'Avg Rating',
    'servicesPage.availability': 'Availability',
    'servicesPage.ourServices': 'Our Services',
    'servicesPage.ourServicesDesc': 'Choose from our wide range of professional home services',
    'servicesPage.allServices': 'All Services',
    'servicesPage.noServices': 'No services found',
    'servicesPage.clearSearch': 'Clear filters',
    'servicesPage.topProviders': 'Top Rated Providers',
    'servicesPage.topProvidersDesc': 'Handpicked professionals with the highest ratings',
    'servicesPage.verified': 'Verified',
    'servicesPage.available': 'Available',
    'servicesPage.callNow': 'Call Now',
    'servicesPage.serviceAreas': 'Service Areas',
    'servicesPage.serviceAreasDesc': 'We cover major areas across Cairo',
    'servicesPage.howItWorks': 'How It Works',
    'servicesPage.howItWorksDesc': 'Book a service in 3 simple steps',
    'servicesPage.step1': 'Choose Service',
    'servicesPage.step1Desc': 'Browse our categories and select the service you need',
    'servicesPage.step2': 'Select Location',
    'servicesPage.step2Desc': 'Pick your area to find nearby service providers',
    'servicesPage.step3': 'Contact Provider',
    'servicesPage.step3Desc': 'Call or message the provider directly to book',
    'servicesPage.needHelp': 'Need Help Finding a Service?',
    'servicesPage.needHelpDesc': "Can't find what you're looking for? Contact us and we'll connect you with the right professional.",
    'servicesPage.backToHome': 'Back to Home',
    'servicesPage.browseProperties': 'Browse Properties',
    'servicesPage.view': 'View',
    'servicesPage.providers2': 'providers',

    // Post Page
    'post.title': 'Create Post',
    'post.subtitle': 'Find a roommate or room',
    'post.type': 'Post Type',
    'post.property': 'Property',
    'post.propertyDesc': 'List a property',
    'post.lookingRoommate': 'Looking for Roommate',
    'post.lookingRoommateDesc': 'Find someone to share',
    'post.lookingRoom': 'Looking for Room',
    'post.lookingRoomDesc': 'Find a place to stay',
    'post.titleLabel': 'Title',
    'post.description': 'Description',
    'post.descriptionPlaceholder': 'Describe your property or requirements...',

    // How It Works
    'howItWorks.whyTitle': 'Why Choose Us',
    'howItWorks.mainTitle': 'We care about your',
    'howItWorks.mainTitleHighlight': 'home search',
    'howItWorks.mainTitleEnd': 'experience',
    'howItWorks.verified': 'Verified Properties',
    'howItWorks.verifiedDesc': 'All properties are verified and inspected for your safety',
    'howItWorks.trusted': 'Trusted Landlords',
    'howItWorks.trustedDesc': 'Connect with verified and trusted property owners',
    'howItWorks.communication': 'Easy Communication',
    'howItWorks.communicationDesc': 'Direct messaging with property owners and quick responses',
    'howItWorks.secure': 'Secure Payments',
    'howItWorks.secureDesc': 'Safe and transparent rental agreements and transactions',
    'howItWorks.title': 'How it Works?',
    'howItWorks.subtitle': 'Follow these 4 simple steps to find and move into your perfect student home in Egypt.',
    'howItWorks.step1': 'Search',
    'howItWorks.step1Desc': 'Find properties near your university.',
    'howItWorks.step2': 'Details',
    'howItWorks.step2Desc': 'Check photos, amenities, and reviews.',
    'howItWorks.step3': 'Contact',
    'howItWorks.step3Desc': 'Message owners and schedule visits.',
    'howItWorks.step4': 'Move In',
    'howItWorks.step4Desc': 'Complete booking and get your keys.',
    'howItWorks.cta': 'Start Searching Now',

    // Common / Language Switcher
    'changeLanguage': 'Language',
    'common.selectLanguage': 'Select Language',
    'propertiesPage.search': 'Search properties...',

    // NewProjectsSection
    'newProjects.badge': 'Featured Collection',
    'newProjects.title': 'Featured',
    'newProjects.titleHighlight': 'Properties',
    'newProjects.from': 'from',
    'newProjects.beds': 'Beds',
    'newProjects.noProperties': 'No matching properties',
    'newProjects.noPropertiesDesc': 'Try changing the city or check back later.',
    'newProjects.exploreAll': 'Explore Full Collection',
    'newProjects.residential': 'Residential',
    'newProjects.today': 'Today',

    // ServicesSection
    'servicesSection.badge': 'Extra Comfort',
    'servicesSection.desc': 'Professional maintenance, cleaning, and support services to make your student life easier.',
    'servicesSection.experts': 'Experts',

    // Footer
    'footer.tagline': 'Your trusted platform for student housing and home services in Egypt',
    'footer.forStudents': 'For Students',
    'footer.findHousing': 'Find Housing',
    'footer.findRoommates': 'Find Roommates',
    'footer.postAd': 'Post Ad',
    'footer.saveProperties': 'Save Properties',
    'footer.forOwners': 'For Owners',
    'footer.listProperty': 'List Property',
    'footer.manageListings': 'Manage Listings',
    'footer.pricing': 'Pricing',
    'footer.resources': 'Resources',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Baytino. All rights reserved.',

    // PropertiesSection (home)
    'properties.premiumListings': 'Premium Listings',
    'properties.latestBadge': 'Latest Posts',
    'properties.featuredPosts': 'Featured Posts',
    'properties.premiumDesc': 'Carefully curated student housing options designed for comfort and success.',
    'properties.featuredBadge': 'Featured',
    'properties.egpPerMonth': 'EGP/mo',
    'properties.noListings': 'No active listings',
    'properties.noListingsDesc': "We're currently updating our catalog. Please check back in a few hours!",
    'properties.exploreAll': 'Explore All Properties',

    // NewProjectsSection – location-based keys
    'newProjects.locationBadge': 'Browse by Area',
    'newProjects.locationTitle': 'Posts by',
    'newProjects.locationHighlight': 'Location',
    'newProjects.allCities': 'All',

    // Login page
    'login.welcomeBack': 'Welcome back! Sign in to continue',
    'login.createAccount': 'Create your account to get started',
    'login.continueGoogle': 'Continue with Google',
    'login.continueFacebook': 'Continue with Facebook',
    'login.or': 'OR',
    'login.loginTab': 'Login',
    'login.signUpTab': 'Sign Up',
    'login.fullName': 'Full Name',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.iAmA': 'I am a:',
    'login.student': 'Student',
    'login.agent': 'Agent',
    'login.propertyOwner': 'Property Owner',
    'login.serviceProvider': 'Service Provider',
    'login.forgotPassword': 'Forgot password?',
    'login.createAccountBtn': '🚀 CREATE ACCOUNT',
    'login.loginBtn': '🔓 LOGIN',
    'login.pleaseWait': 'Please wait...',
    'login.backToHome': '← Back to Home',
    'login.newToBaytino': 'New to Baytino?',
    'login.newDesc': 'Create your account to access housing, roommates, and home services!',
    'login.noAccount': "Don't have an account?",
    'login.signUpNow': 'Sign up now',
    'login.minChars': 'Must be at least 6 characters',

    // Service names and descriptions
    'service.plumbing.name': 'Plumbing',
    'service.plumbing.desc': 'Professional plumbers for all your water and pipe needs',
    'service.electrical.name': 'Electrical',
    'service.electrical.desc': 'Licensed electricians for safe and reliable electrical work',
    'service.cleaning.name': 'Cleaning',
    'service.cleaning.desc': 'Professional cleaning services for homes and offices',
    'service.ac.name': 'AC Repair',
    'service.ac.desc': 'Expert AC repair and maintenance for all brands',
    'service.painting.name': 'Painting',
    'service.painting.desc': 'Professional painters for interior and exterior work',
    'service.carpentry.name': 'Carpentry',
    'service.carpentry.desc': 'Skilled carpenters for custom furniture and repairs',

    // Property types
    'propertyType.apartment': 'Apartment',
    'propertyType.house': 'House',
    'propertyType.villa': 'Villa',
    'propertyType.room': 'Room',
    'propertyType.studio': 'Studio',
    'propertyType.property': 'Property',
    'propertyType.roommate': 'Roommate',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.properties': 'العقارات',
    'nav.services': 'الخدمات',
    'nav.login': 'تسجيل الدخول',
    'nav.getStarted': 'ابدأ',
    'nav.dashboard': 'لوحة التحكم',
    'nav.settings': 'الإعدادات',
    'nav.createPost': 'إنشاء منشور',
    'nav.logout': 'خروج',
    'hero.title': 'ابحث عن سكن طلابي مثالي',
    'hero.subtitle': 'ابحث عن عقارات للإيجار، زملاء السكن، والشقق المشتركة',
    'hero.location': 'الموقع',
    'hero.propertyType': 'نوع العقار',
    'hero.priceRange': 'نطاق السعر',
    'hero.search': 'بحث',
    'hero.apartment': 'شقة',
    'hero.room': 'غرفة',
    'hero.roommate': 'زميل سكن',
    'stats.properties': 'عقارات',
    'stats.students': 'طلاب',
    'stats.agents': 'وكلاء',
    'stats.satisfied': 'عملاء راضون',
    'properties.featured': 'عقارات مميزة',
    'properties.viewAll': 'عرض الكل',
    'properties.bedrooms': 'غرف نوم',
    'properties.bathrooms': 'حمامات',
    'properties.area': 'المساحة',
    'properties.month': 'شهر',
    'propertiesPage.title': 'تصفح العقارات',
    'propertiesPage.subtitle': 'اعثر على منزلك المثالي في مصر',
    'propertiesPage.filters': 'الفلاتر',
    'propertiesPage.city': 'الموقع',
    'propertiesPage.type': 'النوع',
    'propertiesPage.price': 'السعر (جنيه)',
    'propertiesPage.minPrice': 'الحد الأدنى',
    'propertiesPage.maxPrice': 'الحد الأقصى',
    'propertiesPage.clearFilters': 'مسح الفلاتر',
    'propertiesPage.found': 'تم العثور على',
    'propertiesPage.noProperties': 'لا توجد عقارات',
    'propertiesPage.adjustFilters': 'حاول تعديل الفلاتر',
    'propertiesPage.viewDetails': 'عرض التفاصيل',
    'propertiesPage.whatsapp': 'واتساب',
    'propertiesPage.views': 'مشاهدات',
    'propertiesPage.likes': 'إعجابات',
    'propertiesPage.loading': 'جار تحميل العقارات...',
    'propertiesPage.allAreas': 'جميع المناطق',
    'propertiesPage.cairoAll': 'القاهرة (الكل)',
    'propertiesPage.allTypes': 'جميع الأنواع',
    'propertiesPage.propertyType': 'عقار',
    'propertiesPage.roomType': 'غرفة',
    'propertiesPage.roommateType': 'زميل سكن',
    'propertiesPage.any': 'أي',
    'propertiesPage.reset': 'إعادة تعيين',
    'propertiesPage.apply': 'تطبيق',
    'propertiesPage.addProperty': 'إضافة عقار',
    'propertiesPage.notAvailable': 'غير متاح',
    'propertiesPage.restore': 'استعادة',
    'propertiesPage.br': 'غرف',
    'propertiesPage.ba': 'حمام',
    'propertiesPage.more': 'المزيد',
    'detail.backToProperties': 'العودة للعقارات',
    'detail.home': 'الرئيسية',
    'detail.properties': 'العقارات',
    'detail.share': 'مشاركة',
    'detail.monthlyRent': 'الإيجار الشهري',
    'detail.propertyDetails': 'تفاصيل العقار',
    'detail.description': 'الوصف',
    'detail.amenities': 'المرافق والميزات',
    'detail.preferences': 'التفضيلات',
    'detail.videos': 'فيديوهات العقار',
    'detail.postedBy': 'نُشر بواسطة',
    'detail.yourProperty': 'عقارك',
    'detail.manageProperty': 'إدارة القائمة',
    'detail.editProperty': 'تعديل العقار',
    'detail.deleteProperty': 'حذف العقار',
    'detail.deleting': 'جار الحذف...',
    'detail.contactWhatsapp': 'تواصل عبر واتساب',
    'detail.directMessage': 'رسالة مباشرة لمالك العقار',
    'detail.safetyTips': 'نصائح الأمان',
    'detail.safetyTip1': 'قم دائمًا بزيارة العقار شخصيًا قبل الدفع',
    'detail.safetyTip2': 'لا تحول أموالاً بدون رؤية العقار أولاً',
    'detail.safetyTip3': 'تحقق من هوية مالك العقار',
    'detail.notFound': 'لم يتم العثور على العقار',
    'detail.notFoundDesc': 'ربما تم إزالة هذا القائمة أو لم تعد متاحة.',
    'detail.forFamily': 'للعائلة',
    'detail.forStudents': 'للطلاب',
    'detail.furnished': 'مفروش',
    'detail.type': 'النوع',
    'detail.memberSince': 'عضو منذ',
    'detail.viewAllPhotos': 'عرض جميع الصور',
    'services.title': 'خدمات المنزل',
    'services.viewProviders': 'عرض مقدمي الخدمة',
    'servicesPage.heroTitle': 'خدمات المنزل على بابك',
    'servicesPage.heroSubtitle': 'اعثر على محترفين موثوقين للسباكة والكهرباء والتنظيف وإصلاح التكييف والدهان والنجارة في القاهرة.',
    'servicesPage.searchPlaceholder': 'ابحث عن خدمة...',
    'servicesPage.providers': 'مقدمو الخدمات',
    'servicesPage.categories': 'فئات الخدمات',
    'servicesPage.avgRating': 'متوسط التقييم',
    'servicesPage.availability': 'التوفر',
    'servicesPage.ourServices': 'خدماتنا',
    'servicesPage.ourServicesDesc': 'اختر من مجموعتنا الواسعة من الخدمات المنزلية المهنية',
    'servicesPage.allServices': 'جميع الخدمات',
    'servicesPage.noServices': 'لم يتم العثور على خدمات',
    'servicesPage.clearSearch': 'مسح الفلاتر',
    'servicesPage.topProviders': 'أفضل مقدمي الخدمات',
    'servicesPage.topProvidersDesc': 'محترفون مختارون بأعلى التقييمات',
    'servicesPage.verified': 'موثق',
    'servicesPage.available': 'متاح',
    'servicesPage.callNow': 'اتصل الآن',
    'servicesPage.serviceAreas': 'مناطق الخدمة',
    'servicesPage.serviceAreasDesc': 'نغطي المناطق الرئيسية في القاهرة',
    'servicesPage.howItWorks': 'كيف يعمل',
    'servicesPage.howItWorksDesc': 'احجز خدمة في ٣ خطوات بسيطة',
    'servicesPage.step1': 'اختر الخدمة',
    'servicesPage.step1Desc': 'تصفح الفئات واختر الخدمة التي تحتاجها',
    'servicesPage.step2': 'اختر الموقع',
    'servicesPage.step2Desc': 'حدد منطقتك للعثور على مقدمي الخدمات القريبين',
    'servicesPage.step3': 'تواصل مع مقدم الخدمة',
    'servicesPage.step3Desc': 'اتصل أو راسل مقدم الخدمة مباشرة للحجز',
    'servicesPage.needHelp': 'تحتاج مساعدة في إيجاد خدمة؟',
    'servicesPage.needHelpDesc': 'لا تجد ما تبحث عنه؟ تواصل معنا وسنوصلك بالمحترف المناسب.',
    'servicesPage.backToHome': 'العودة للرئيسية',
    'servicesPage.browseProperties': 'تصفح العقارات',
    'servicesPage.view': 'عرض',
    'servicesPage.providers2': 'مقدم خدمة',
    'post.title': 'إنشاء منشور',
    'post.subtitle': 'ابحث عن زميل سكن أو غرفة',
    'post.type': 'نوع المنشور',
    'post.property': 'عقار',
    'post.propertyDesc': 'أضف عقار',
    'post.lookingRoommate': 'البحث عن زميل سكن',
    'post.lookingRoommateDesc': 'ابحث عن شخص للمشاركة',
    'post.lookingRoom': 'البحث عن غرفة',
    'post.lookingRoomDesc': 'ابحث عن مكان للإقامة',
    'post.titleLabel': 'العنوان',
    'post.description': 'الوصف',
    'post.descriptionPlaceholder': 'صف عقارك أو متطلباتك...',
    'howItWorks.whyTitle': 'لماذا تختارنا',
    'howItWorks.mainTitle': 'نحن نهتم ب',
    'howItWorks.mainTitleHighlight': 'تجربة البحث',
    'howItWorks.mainTitleEnd': 'عن المنزل',
    'howItWorks.verified': 'عقارات موثقة',
    'howItWorks.verifiedDesc': 'جميع العقارات موثقة ومفتشة من أجل سلامتك',
    'howItWorks.trusted': 'ملاك موثوقون',
    'howItWorks.trustedDesc': 'تواصل مع أصحاب عقارات موثقين وموثوقين',
    'howItWorks.communication': 'تواصل سهل',
    'howItWorks.communicationDesc': 'مراسلة مباشرة مع أصحاب العقارات واستجابة سريعة',
    'howItWorks.secure': 'دفع آمن',
    'howItWorks.secureDesc': 'اتفاقيات إيجار آمنة وشفافة ومعاملات موثوقة',
    'howItWorks.title': 'كيف يعمل؟',
    'howItWorks.subtitle': 'اتبع هذه الخطوات الأربع البسيطة للعثور على منزل الطالب المثالي والانتقال إليه في مصر.',
    'howItWorks.step1': 'البحث',
    'howItWorks.step1Desc': 'ابحث عن عقارات بالقرب من جامعتك.',
    'howItWorks.step2': 'التفاصيل',
    'howItWorks.step2Desc': 'تحقق من الصور والمرافق والتقييمات.',
    'howItWorks.step3': 'الاتصال',
    'howItWorks.step3Desc': 'راسل المالكين وحدد مواعيد الزيارات.',
    'howItWorks.step4': 'الانتقال',
    'howItWorks.step4Desc': 'أكمل الحجز واحصل على مفاتيحك.',
    'howItWorks.cta': 'ابدأ البحث الآن',
    'changeLanguage': 'اللغة',
    'common.selectLanguage': 'اختر اللغة',
    'propertiesPage.search': 'ابحث في العقارات...',
    'newProjects.badge': 'مجموعة مميزة',
    'newProjects.title': 'عقارات',
    'newProjects.titleHighlight': 'مميزة',
    'newProjects.from': 'من',
    'newProjects.beds': 'غرف',
    'newProjects.noProperties': 'لا توجد عقارات',
    'newProjects.noPropertiesDesc': 'جرب تغيير المدينة أو تحقق لاحقاً.',
    'newProjects.exploreAll': 'استكشف جميع العقارات',
    'newProjects.residential': 'سكني',
    'newProjects.today': 'اليوم',
    'servicesSection.badge': 'راحة إضافية',
    'servicesSection.desc': 'خدمات صيانة واحترافية لتجعل حياتك الطلابية أسهل.',
    'servicesSection.experts': 'خبراء',
    'footer.tagline': 'منصتك الموثوقة للإسكان الطلابي وخدمات المنزل في مصر',
    'footer.forStudents': 'للطلاب',
    'footer.findHousing': 'ابحث عن مسكن',
    'footer.findRoommates': 'ابحث عن زملاء',
    'footer.postAd': 'أضف إعلان',
    'footer.saveProperties': 'احفظ العقارات',
    'footer.forOwners': 'لأصحاب العقارات',
    'footer.listProperty': 'أضف عقاراً',
    'footer.manageListings': 'إدارة القوائم',
    'footer.pricing': 'الأسعار',
    'footer.resources': 'الموارد',
    'footer.company': 'الشركة',
    'footer.aboutUs': 'من نحن',
    'footer.contact': 'اتصل بنا',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.copyright': '© 2025 Baytino. جميع الحقوق محفوظة.',
    'properties.premiumListings': 'إعلانات مميزة',
    'properties.latestBadge': 'أحدث المنشورات',
    'properties.featuredPosts': 'منشورات مميزة',
    'properties.premiumDesc': 'خيارات سكن طلابي مختارة بعناية صممت للراحة والنجاح.',
    'properties.featuredBadge': 'مميز',
    'properties.egpPerMonth': 'ج.م/شهر',
    'properties.noListings': 'لا توجد إعلانات نشطة',
    'properties.noListingsDesc': 'نحن نحدث قائمتنا حاليًا. يرجى التحقق مرة أخرى بعد بضع ساعات!',
    'properties.exploreAll': 'استكشف جميع العقارات',
    'newProjects.locationBadge': 'تصفح حسب المنطقة',
    'newProjects.locationTitle': 'منشورات حسب',
    'newProjects.locationHighlight': 'الموقع',
    'newProjects.allCities': 'الكل',
    'login.welcomeBack': 'مرحبًا بعودتك! سجّل الدخول للمتابعة',
    'login.createAccount': 'أنشئ حسابك للبدء',
    'login.continueGoogle': 'المتابعة بـ Google',
    'login.continueFacebook': 'المتابعة بـ Facebook',
    'login.or': 'أو',
    'login.loginTab': 'تسجيل الدخول',
    'login.signUpTab': 'إنشاء حساب',
    'login.fullName': 'الاسم الكامل',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.iAmA': 'أنا:',
    'login.student': 'طالب',
    'login.agent': 'وكيل',
    'login.propertyOwner': 'مالك عقار',
    'login.serviceProvider': 'مزوّد خدمة',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.createAccountBtn': '🚀 إنشاء حساب',
    'login.loginBtn': '🔓 تسجيل الدخول',
    'login.pleaseWait': 'يرجى الانتظار...',
    'login.backToHome': '← العودة للرئيسية',
    'login.newToBaytino': 'جديد في Baytino؟',
    'login.newDesc': 'أنشئ حسابك للوصول إلى السكن وزملاء السكن وخدمات المنزل!',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.signUpNow': 'سجّل الآن',
    'login.minChars': 'يجب أن تكون 6 أحرف على الأقل',
    'service.plumbing.name': 'السباكة',
    'service.plumbing.desc': 'سباكون محترفون لجميع احتياجاتك المائية والأنابيب',
    'service.electrical.name': 'الكهرباء',
    'service.electrical.desc': 'كهربائيون مرخصون لأعمال كهربائية آمنة وموثوقة',
    'service.cleaning.name': 'التنظيف',
    'service.cleaning.desc': 'خدمات تنظيف احترافية للمنازل والمكاتب',
    'service.ac.name': 'إصلاح التكييف',
    'service.ac.desc': 'خبراء في إصلاح وصيانة أجهزة التكييف لجميع الماركات',
    'service.painting.name': 'الدهان',
    'service.painting.desc': 'دهانون محترفون للأعمال الداخلية والخارجية',
    'service.carpentry.name': 'النجارة',
    'service.carpentry.desc': 'نجارون ماهرون للأثاث المخصص والإصلاحات',
    'propertyType.apartment': 'شقة',
    'propertyType.house': 'منزل',
    'propertyType.villa': 'فيلا',
    'propertyType.room': 'غرفة',
    'propertyType.studio': 'استوديو',
    'propertyType.property': 'عقار',
    'propertyType.roommate': 'زميل سكن',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.properties': 'প্রপার্টি',
    'nav.services': 'সেবা',
    'nav.login': 'লগইন',
    'nav.getStarted': 'শুরু করুন',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.settings': 'সেটিংস',
    'nav.createPost': 'পোস্ট করুন',
    'nav.logout': 'লগআউট',
    'hero.title': 'আপনার পারফেক্ট স্টুডেন্ট হাউজিং খুঁজুন',
    'hero.subtitle': 'ভাড়া, রুমমেট এবং শেয়ার্ড অ্যাপার্টমেন্টের জন্য প্রপার্টি খুঁজুন',
    'hero.location': 'লোকেশন',
    'hero.propertyType': 'প্রপার্টির ধরন',
    'hero.priceRange': 'মূল্য সীমা',
    'hero.search': 'খুঁজুন',
    'hero.apartment': 'অ্যাপার্টমেন্ট',
    'hero.room': 'রুম',
    'hero.roommate': 'রুমমেট',
    'stats.properties': 'প্রপার্টি',
    'stats.students': 'স্টুডেন্ট',
    'stats.agents': 'এজেন্ট',
    'stats.satisfied': 'সন্তুষ্ট ক্লায়েন্ট',
    'properties.featured': 'ফিচার্ড প্রপার্টি',
    'properties.viewAll': 'সব দেখুন',
    'properties.bedrooms': 'বেডরুম',
    'properties.bathrooms': 'বাথরুম',
    'properties.area': 'এরিয়া',
    'properties.month': 'মাস',
    'propertiesPage.title': 'প্রপার্টি ব্রাউজ করুন',
    'propertiesPage.subtitle': 'মিশরে আপনার পারফেক্ট বাড়ি খুঁজুন',
    'propertiesPage.filters': 'ফিল্টার',
    'propertiesPage.city': 'লোকেশন',
    'propertiesPage.type': 'টাইপ',
    'propertiesPage.price': 'মূল্য (EGP)',
    'propertiesPage.minPrice': 'মিনিমাম',
    'propertiesPage.maxPrice': 'ম্যাক্সিমাম',
    'propertiesPage.clearFilters': 'ফিল্টার ক্লিয়ার করুন',
    'propertiesPage.found': 'পাওয়া গেছে',
    'propertiesPage.noProperties': 'কোনো প্রপার্টি পাওয়া যায়নি',
    'propertiesPage.adjustFilters': 'ফিল্টার পরিবর্তন করে দেখুন',
    'propertiesPage.viewDetails': 'বিস্তারিত দেখুন',
    'propertiesPage.whatsapp': 'হোয়াটসঅ্যাপ',
    'propertiesPage.views': 'ভিউ',
    'propertiesPage.likes': 'লাইক',
    'propertiesPage.loading': 'প্রপার্টি লোড হচ্ছে...',
    'propertiesPage.allAreas': 'সব এলাকা',
    'propertiesPage.cairoAll': 'কায়রো (সব)',
    'propertiesPage.allTypes': 'সব ধরন',
    'propertiesPage.propertyType': 'প্রপার্টি',
    'propertiesPage.roomType': 'রুম',
    'propertiesPage.roommateType': 'রুমমেট',
    'propertiesPage.any': 'যেকোনো',
    'propertiesPage.reset': 'রিসেট',
    'propertiesPage.apply': 'প্রয়োগ',
    'propertiesPage.addProperty': 'প্রপার্টি যোগ করুন',
    'propertiesPage.notAvailable': 'পাওয়া যাচ্ছে না',
    'propertiesPage.restore': 'পুনরুদ্ধার',
    'propertiesPage.br': 'বেড',
    'propertiesPage.ba': 'বাথ',
    'propertiesPage.more': 'আরো',
    'detail.backToProperties': 'প্রপার্টিতে ফিরুন',
    'detail.home': 'হোম',
    'detail.properties': 'প্রপার্টি',
    'detail.share': 'শেয়ার',
    'detail.monthlyRent': 'মাসিক ভাড়া',
    'detail.propertyDetails': 'প্রপার্টির বিবরণ',
    'detail.description': 'বর্ণনা',
    'detail.amenities': 'সুবিধা ও বৈশিষ্ট্য',
    'detail.preferences': 'পছন্দ',
    'detail.videos': 'প্রপার্টি ভিডিও',
    'detail.postedBy': 'পোস্ট করেছেন',
    'detail.yourProperty': 'আপনার প্রপার্টি',
    'detail.manageProperty': 'আপনার লিস্টিং পরিচালনা করুন',
    'detail.editProperty': 'প্রপার্টি এডিট করুন',
    'detail.deleteProperty': 'প্রপার্টি ডিলিট করুন',
    'detail.deleting': 'ডিলিট হচ্ছে...',
    'detail.contactWhatsapp': 'হোয়াটসঅ্যাপে যোগাযোগ করুন',
    'detail.directMessage': 'প্রপার্টি মালিককে সরাসরি মেসেজ করুন',
    'detail.safetyTips': 'নিরাপত্তা টিপস',
    'detail.safetyTip1': 'পেমেন্ট করার আগে সবসময় ব্যক্তিগতভাবে প্রপার্টি দেখুন',
    'detail.safetyTip2': 'প্রপার্টি না দেখে কখনো টাকা পাঠাবেন না',
    'detail.safetyTip3': 'প্রপার্টি মালিকের পরিচয় যাচাই করুন',
    'detail.notFound': 'প্রপার্টি পাওয়া যায়নি',
    'detail.notFoundDesc': 'এই লিস্টিংটি মুছে ফেলা হয়েছে বা আর পাওয়া যাচ্ছে না।',
    'detail.forFamily': 'পরিবারের জন্য',
    'detail.forStudents': 'শিক্ষার্থীদের জন্য',
    'detail.furnished': 'ফার্নিশড',
    'detail.type': 'ধরন',
    'detail.memberSince': 'সদস্য',
    'detail.viewAllPhotos': 'সব ছবি দেখুন',
    'services.title': 'হোম সার্ভিস',
    'services.viewProviders': 'প্রোভাইডার দেখুন',
    'servicesPage.heroTitle': 'আপনার দোরগোড়ায় হোম সার্ভিস',
    'servicesPage.heroSubtitle': 'কায়রো জুড়ে প্লাম্বিং, ইলেকট্রিক্যাল, ক্লিনিং, এসি মেরামত, পেইন্টিং এবং কার্পেন্ট্রি সেবার জন্য বিশ্বস্ত পেশাদার খুঁজুন।',
    'servicesPage.searchPlaceholder': 'সার্ভিস খুঁজুন...',
    'servicesPage.providers': 'সেবা প্রদানকারী',
    'servicesPage.categories': 'সেবা ক্যাটাগরি',
    'servicesPage.avgRating': 'গড় রেটিং',
    'servicesPage.availability': 'সময়সূচি',
    'servicesPage.ourServices': 'আমাদের সেবা',
    'servicesPage.ourServicesDesc': 'আমাদের পেশাদার হোম সার্ভিসের বিস্তৃত পরিসর থেকে বেছে নিন',
    'servicesPage.allServices': 'সব সেবা',
    'servicesPage.noServices': 'কোনো সেবা পাওয়া যায়নি',
    'servicesPage.clearSearch': 'ফিল্টার মুছুন',
    'servicesPage.topProviders': 'সেরা প্রোভাইডার',
    'servicesPage.topProvidersDesc': 'সর্বোচ্চ রেটিং সহ নির্বাচিত পেশাদার',
    'servicesPage.verified': 'যাচাইকৃত',
    'servicesPage.available': 'পাওয়া যায়',
    'servicesPage.callNow': 'এখনই কল করুন',
    'servicesPage.serviceAreas': 'সেবা এলাকা',
    'servicesPage.serviceAreasDesc': 'আমরা কায়রো জুড়ে প্রধান এলাকাগুলো কভার করি',
    'servicesPage.howItWorks': 'এটি কিভাবে কাজ করে',
    'servicesPage.howItWorksDesc': '৩টি সহজ ধাপে সেবা বুক করুন',
    'servicesPage.step1': 'সেবা বেছে নিন',
    'servicesPage.step1Desc': 'ক্যাটাগরি ব্রাউজ করুন এবং আপনার প্রয়োজনীয় সেবা নির্বাচন করুন',
    'servicesPage.step2': 'লোকেশন নির্বাচন করুন',
    'servicesPage.step2Desc': 'কাছাকাছি সেবা প্রদানকারী খুঁজতে আপনার এলাকা বাছুন',
    'servicesPage.step3': 'প্রোভাইডারে যোগাযোগ করুন',
    'servicesPage.step3Desc': 'বুক করতে সরাসরি কল বা মেসেজ করুন',
    'servicesPage.needHelp': 'সেবা খুঁজতে সাহায্য লাগছে?',
    'servicesPage.needHelpDesc': 'যা খুঁজছেন তা পাচ্ছেন না? আমাদের সাথে যোগাযোগ করুন।',
    'servicesPage.backToHome': 'হোমে ফিরুন',
    'servicesPage.browseProperties': 'প্রপার্টি ব্রাউজ করুন',
    'servicesPage.view': 'দেখুন',
    'servicesPage.providers2': 'প্রোভাইডার',
    'post.title': 'পোস্ট তৈরি করুন',
    'post.subtitle': 'রুমমেট বা রুম খুঁজুন',
    'post.type': 'পোস্ট টাইপ',
    'post.property': 'প্রপার্টি',
    'post.propertyDesc': 'প্রপার্টি লিস্ট করুন',
    'post.lookingRoommate': 'রুমমেট খুঁজছি',
    'post.lookingRoommateDesc': 'শেয়ার করার জন্য কাউকে খুঁজুন',
    'post.lookingRoom': 'রুম খুঁজছি',
    'post.lookingRoomDesc': 'থাকার জায়গা খুঁজুন',
    'post.titleLabel': 'শিরোনাম',
    'post.description': 'বিবরণ',
    'post.descriptionPlaceholder': 'আপনার প্রপার্টি বা প্রয়োজনীয়তা বর্ণনা করুন...',
    'howItWorks.whyTitle': 'কেন আমাদের বেছে নেবেন',
    'howItWorks.mainTitle': 'আমরা আপনার',
    'howItWorks.mainTitleHighlight': 'বাড়ি খোঁজার',
    'howItWorks.mainTitleEnd': 'অভিজ্ঞতার যত্ন নিই',
    'howItWorks.verified': 'যাচাইকৃত প্রপার্টি',
    'howItWorks.verifiedDesc': 'সব প্রপার্টি আপনার নিরাপত্তার জন্য যাচাই ও পরিদর্শন করা',
    'howItWorks.trusted': 'বিশ্বস্ত বাড়িওয়ালা',
    'howItWorks.trustedDesc': 'যাচাইকৃত এবং বিশ্বস্ত প্রপার্টি মালিকদের সাথে সংযোগ করুন',
    'howItWorks.communication': 'সহজ যোগাযোগ',
    'howItWorks.communicationDesc': 'প্রপার্টি মালিকদের সাথে সরাসরি মেসেজিং এবং দ্রুত প্রতিক্রিয়া',
    'howItWorks.secure': 'নিরাপদ পেমেন্ট',
    'howItWorks.secureDesc': 'নিরাপদ এবং স্বচ্ছ ভাড়া চুক্তি এবং লেনদেন',
    'howItWorks.title': 'এটি কিভাবে কাজ করে?',
    'howItWorks.subtitle': 'মিশরে আপনার নিখুঁত স্টুডেন্ট হোম খুঁজে পেতে এবং সেখানে যেতে এই ৪টি সহজ ধাপ অনুসরণ করুন।',
    'howItWorks.step1': 'খুঁজুন',
    'howItWorks.step1Desc': 'আপনার বিশ্ববিদ্যালয়ের কাছাকাছি প্রপার্টি খুঁজুন।',
    'howItWorks.step2': 'বিবরণ',
    'howItWorks.step2Desc': 'ছবি, সুবিধা এবং রিভিউ চেক করুন।',
    'howItWorks.step3': 'যোগাযোগ',
    'howItWorks.step3Desc': 'মালিকদের মেসেজ করুন এবং ভিজিট শিডিউল করুন।',
    'howItWorks.step4': 'মুভ ইন',
    'howItWorks.step4Desc': 'বুকিং সম্পূর্ণ করুন এবং আপনার চাবি নিন।',
    'howItWorks.cta': 'এখনই খোঁজা শুরু করুন',
    'changeLanguage': 'ভাষা',
    'common.selectLanguage': 'ভাষা নির্বাচন করুন',
    'propertiesPage.search': 'প্রপার্টি খুঁজুন...',
    'newProjects.badge': 'বিশেষ সংগ্রহ',
    'newProjects.title': 'বিশেষ',
    'newProjects.titleHighlight': 'প্রপার্টি',
    'newProjects.from': 'থেকে',
    'newProjects.beds': 'বেড',
    'newProjects.noProperties': 'কোনো প্রপার্টি পাওয়া যায়নি',
    'newProjects.noPropertiesDesc': 'শহর পরিবর্তন করে দেখুন।',
    'newProjects.exploreAll': 'সব প্রপার্টি দেখুন',
    'newProjects.residential': 'আবাসিক',
    'newProjects.today': 'আজ',
    'servicesSection.badge': 'অতিরিক্ত আরাম',
    'servicesSection.desc': 'পেশাদার রক্ষণাবেক্ষণ ও সহায়তা সেবা আপনার ছাত্রজীবনকে সহজ করতে।',
    'servicesSection.experts': 'বিশেষজ্ঞ',
    'footer.tagline': 'মিশরে শিক্ষার্থী আবাসন ও হোম সার্ভিসের জন্য আপনার বিশ্বস্ত প্ল্যাটফর্ম',
    'footer.forStudents': 'শিক্ষার্থীদের জন্য',
    'footer.findHousing': 'আবাসন খুঁজুন',
    'footer.findRoommates': 'রুমমেট খুঁজুন',
    'footer.postAd': 'বিজ্ঞাপন দিন',
    'footer.saveProperties': 'প্রপার্টি সেভ করুন',
    'footer.forOwners': 'মালিকদের জন্য',
    'footer.listProperty': 'প্রপার্টি লিস্ট করুন',
    'footer.manageListings': 'লিস্টিং পরিচালনা',
    'footer.pricing': 'মূল্য',
    'footer.resources': 'রিসোর্স',
    'footer.company': 'কোম্পানি',
    'footer.aboutUs': 'আমাদের সম্পর্কে',
    'footer.contact': 'যোগাযোগ',
    'footer.privacy': 'গোপনীয়তা নীতি',
    'footer.terms': 'সেবার শর্তাবলী',
    'footer.copyright': '© 2025 Baytino. সর্বস্বত্ব সংরক্ষিত।',
    'properties.premiumListings': 'প্রিমিয়াম লিস্টিং',
    'properties.premiumDesc': 'আরাম ও সাফল্যের জন্য যত্ন সহকারে বাছাই করা শিক্ষার্থী আবাসন বিকল্প।',
    'properties.featuredBadge': 'বিশেষ',
    'properties.egpPerMonth': 'EGP/মাস',
    'properties.noListings': 'কোনো সক্রিয় লিস্টিং নেই',
    'properties.noListingsDesc': 'আমরা আমাদের ক্যাটালগ আপডেট করছি। কয়েক ঘণ্টা পরে আবার দেখুন!',
    'properties.exploreAll': 'সব প্রপার্টি দেখুন',
    'service.plumbing.name': 'প্লাম্বিং',
    'service.plumbing.desc': 'পানি ও পাইপের সব প্রয়োজনে পেশাদার প্লাম্বার',
    'service.electrical.name': 'ইলেকট্রিক্যাল',
    'service.electrical.desc': 'নিরাপদ ও নির্ভরযোগ্য বৈদ্যুতিক কাজের জন্য লাইসেন্সপ্রাপ্ত ইলেকট্রিশিয়ান',
    'service.cleaning.name': 'ক্লিনিং',
    'service.cleaning.desc': 'বাড়ি ও অফিসের জন্য পেশাদার পরিষ্কার সেবা',
    'service.ac.name': 'এসি মেরামত',
    'service.ac.desc': 'সব ব্র্যান্ডের এসি মেরামত ও রক্ষণাবেক্ষণে বিশেষজ্ঞ',
    'service.painting.name': 'পেইন্টিং',
    'service.painting.desc': 'অভ্যন্তরীণ ও বহিরাগত কাজের জন্য পেশাদার পেইন্টার',
    'service.carpentry.name': 'কার্পেন্ট্রি',
    'service.carpentry.desc': 'কাস্টম আসবাবপত্র ও মেরামতের জন্য দক্ষ কার্পেন্টার',
    'propertyType.apartment': 'অ্যাপার্টমেন্ট',
    'propertyType.house': 'বাড়ি',
    'propertyType.villa': 'ভিলা',
    'propertyType.room': 'রুম',
    'propertyType.studio': 'স্টুডিও',
    'propertyType.property': 'প্রপার্টি',
    'propertyType.roommate': 'রুমমেট',
  },
  id: {
    'nav.home': 'Beranda', 'nav.properties': 'Properti', 'nav.services': 'Layanan', 'nav.login': 'Masuk', 'nav.getStarted': 'Mulai', 'nav.dashboard': 'Dasbor', 'nav.settings': 'Pengaturan', 'nav.createPost': 'Buat Post', 'nav.logout': 'Keluar',
    'hero.title': 'Temukan Hunian Mahasiswa Sempurna Anda', 'hero.subtitle': 'Cari properti untuk disewa, teman sekamar, dan apartemen bersama', 'hero.location': 'Lokasi', 'hero.propertyType': 'Tipe Properti', 'hero.priceRange': 'Rentang Harga', 'hero.search': 'Cari', 'hero.apartment': 'Apartemen', 'hero.room': 'Kamar', 'hero.roommate': 'Teman Sekamar',
    'stats.properties': 'Properti', 'stats.students': 'Mahasiswa', 'stats.agents': 'Agen', 'stats.satisfied': 'Klien Puas',
    'properties.featured': 'Properti Unggulan', 'properties.viewAll': 'Lihat Semua', 'properties.bedrooms': 'Kamar Tidur', 'properties.bathrooms': 'Kamar Mandi', 'properties.area': 'Luas', 'properties.month': 'bulan',
    'propertiesPage.title': 'Jelajahi Properti', 'propertiesPage.subtitle': 'Temukan rumah sempurna Anda di Mesir', 'propertiesPage.filters': 'Filter', 'propertiesPage.city': 'Lokasi', 'propertiesPage.type': 'Tipe', 'propertiesPage.price': 'Harga (EGP)', 'propertiesPage.minPrice': 'Harga Min', 'propertiesPage.maxPrice': 'Harga Maks', 'propertiesPage.clearFilters': 'Hapus Filter', 'propertiesPage.found': 'Ditemukan', 'propertiesPage.noProperties': 'Tidak ada properti', 'propertiesPage.adjustFilters': 'Coba sesuaikan filter Anda', 'propertiesPage.viewDetails': 'Lihat Detail', 'propertiesPage.whatsapp': 'WhatsApp', 'propertiesPage.views': 'tampilan', 'propertiesPage.likes': 'suka',
    'propertiesPage.loading': 'Memuat properti...', 'propertiesPage.allAreas': 'Semua Area', 'propertiesPage.cairoAll': 'Kairo (Semua)', 'propertiesPage.allTypes': 'Semua Tipe', 'propertiesPage.propertyType': 'Properti', 'propertiesPage.roomType': 'Kamar', 'propertiesPage.roommateType': 'Teman Sekamar', 'propertiesPage.any': 'Semua', 'propertiesPage.reset': 'Reset', 'propertiesPage.apply': 'Terapkan', 'propertiesPage.addProperty': 'Tambah Properti', 'propertiesPage.notAvailable': 'Tidak Tersedia', 'propertiesPage.restore': 'Pulihkan', 'propertiesPage.br': 'KT', 'propertiesPage.ba': 'KM', 'propertiesPage.more': 'lagi',
    'detail.backToProperties': 'Kembali', 'detail.home': 'Beranda', 'detail.properties': 'Properti', 'detail.share': 'Bagikan', 'detail.monthlyRent': 'Sewa Bulanan', 'detail.propertyDetails': 'Detail Properti', 'detail.description': 'Deskripsi', 'detail.amenities': 'Fasilitas', 'detail.preferences': 'Preferensi', 'detail.videos': 'Video Properti', 'detail.postedBy': 'Diposting Oleh', 'detail.yourProperty': 'Properti Anda', 'detail.manageProperty': 'Kelola listing Anda', 'detail.editProperty': 'Edit Properti', 'detail.deleteProperty': 'Hapus Properti', 'detail.deleting': 'Menghapus...', 'detail.contactWhatsapp': 'Hubungi via WhatsApp', 'detail.directMessage': 'Pesan langsung ke pemilik properti', 'detail.safetyTips': 'Tips Keamanan', 'detail.safetyTip1': 'Selalu kunjungi properti sebelum membayar', 'detail.safetyTip2': 'Jangan transfer uang tanpa melihat properti', 'detail.safetyTip3': 'Verifikasi identitas pemilik properti', 'detail.notFound': 'Properti tidak ditemukan', 'detail.notFoundDesc': 'Listing ini mungkin telah dihapus.', 'detail.forFamily': 'Untuk Keluarga', 'detail.forStudents': 'Untuk Mahasiswa', 'detail.furnished': 'Berperabotan', 'detail.type': 'Tipe', 'detail.memberSince': 'Anggota sejak', 'detail.viewAllPhotos': 'Lihat semua foto',
    'services.title': 'Layanan Rumah', 'services.viewProviders': 'Lihat Penyedia',
    'servicesPage.heroTitle': 'Layanan Rumah di Depan Pintu Anda', 'servicesPage.heroSubtitle': 'Temukan profesional terpercaya di Kairo.', 'servicesPage.searchPlaceholder': 'Cari layanan...', 'servicesPage.providers': 'Penyedia Layanan', 'servicesPage.categories': 'Kategori', 'servicesPage.avgRating': 'Rating Rata-rata', 'servicesPage.availability': 'Ketersediaan', 'servicesPage.ourServices': 'Layanan Kami', 'servicesPage.ourServicesDesc': 'Pilih dari layanan rumah profesional kami', 'servicesPage.allServices': 'Semua Layanan', 'servicesPage.noServices': 'Layanan tidak ditemukan', 'servicesPage.clearSearch': 'Hapus filter', 'servicesPage.topProviders': 'Penyedia Teratas', 'servicesPage.topProvidersDesc': 'Profesional pilihan dengan rating tertinggi', 'servicesPage.verified': 'Terverifikasi', 'servicesPage.available': 'Tersedia', 'servicesPage.callNow': 'Hubungi', 'servicesPage.serviceAreas': 'Area Layanan', 'servicesPage.serviceAreasDesc': 'Kami melayani area utama di Kairo', 'servicesPage.howItWorks': 'Cara Kerja', 'servicesPage.howItWorksDesc': 'Pesan layanan dalam 3 langkah', 'servicesPage.step1': 'Pilih Layanan', 'servicesPage.step1Desc': 'Pilih layanan yang Anda butuhkan', 'servicesPage.step2': 'Pilih Lokasi', 'servicesPage.step2Desc': 'Temukan penyedia terdekat', 'servicesPage.step3': 'Hubungi', 'servicesPage.step3Desc': 'Hubungi penyedia langsung', 'servicesPage.needHelp': 'Perlu Bantuan?', 'servicesPage.needHelpDesc': 'Hubungi kami.', 'servicesPage.backToHome': 'Kembali', 'servicesPage.browseProperties': 'Lihat Properti', 'servicesPage.view': 'Lihat', 'servicesPage.providers2': 'penyedia',
    'post.title': 'Buat Post', 'post.subtitle': 'Cari teman sekamar atau kamar', 'post.type': 'Tipe Post', 'post.property': 'Properti', 'post.propertyDesc': 'Daftarkan properti', 'post.lookingRoommate': 'Cari Teman Sekamar', 'post.lookingRoommateDesc': 'Cari orang untuk berbagi', 'post.lookingRoom': 'Cari Kamar', 'post.lookingRoomDesc': 'Cari tempat tinggal', 'post.titleLabel': 'Judul', 'post.description': 'Deskripsi', 'post.descriptionPlaceholder': 'Jelaskan properti atau kebutuhan Anda...',
    'howItWorks.whyTitle': 'Mengapa Memilih Kami', 'howItWorks.mainTitle': 'Kami peduli dengan', 'howItWorks.mainTitleHighlight': 'pencarian rumah', 'howItWorks.mainTitleEnd': 'Anda', 'howItWorks.verified': 'Properti Terverifikasi', 'howItWorks.verifiedDesc': 'Semua properti terverifikasi untuk keamanan Anda', 'howItWorks.trusted': 'Pemilik Terpercaya', 'howItWorks.trustedDesc': 'Terhubung dengan pemilik properti terverifikasi', 'howItWorks.communication': 'Komunikasi Mudah', 'howItWorks.communicationDesc': 'Pesan langsung dan respons cepat', 'howItWorks.secure': 'Pembayaran Aman', 'howItWorks.secureDesc': 'Perjanjian sewa yang aman dan transparan', 'howItWorks.title': 'Cara Kerjanya?', 'howItWorks.subtitle': 'Ikuti 4 langkah sederhana ini.', 'howItWorks.step1': 'Cari', 'howItWorks.step1Desc': 'Temukan properti dekat universitas.', 'howItWorks.step2': 'Detail', 'howItWorks.step2Desc': 'Cek foto dan fasilitas.', 'howItWorks.step3': 'Hubungi', 'howItWorks.step3Desc': 'Kirim pesan dan jadwalkan kunjungan.', 'howItWorks.step4': 'Pindah', 'howItWorks.step4Desc': 'Selesaikan booking.', 'howItWorks.cta': 'Mulai Mencari',
    'changeLanguage': 'Bahasa', 'common.selectLanguage': 'Pilih Bahasa', 'propertiesPage.search': 'Cari properti...',
    'newProjects.badge': 'Koleksi Unggulan', 'newProjects.title': 'Properti', 'newProjects.titleHighlight': 'Unggulan', 'newProjects.from': 'dari', 'newProjects.beds': 'Kamar', 'newProjects.noProperties': 'Tidak ada properti', 'newProjects.noPropertiesDesc': 'Coba ganti kota.', 'newProjects.exploreAll': 'Jelajahi Semua', 'newProjects.residential': 'Residensial', 'newProjects.today': 'Hari ini',
    'servicesSection.badge': 'Kenyamanan Ekstra', 'servicesSection.desc': 'Layanan perawatan dan dukungan profesional untuk memudahkan kehidupan mahasiswa Anda.', 'servicesSection.experts': 'Ahli',
    'footer.tagline': 'Platform terpercaya Anda untuk perumahan mahasiswa dan layanan rumah di Mesir', 'footer.forStudents': 'Untuk Mahasiswa', 'footer.findHousing': 'Cari Hunian', 'footer.findRoommates': 'Cari Teman Sekamar', 'footer.postAd': 'Pasang Iklan', 'footer.saveProperties': 'Simpan Properti', 'footer.forOwners': 'Untuk Pemilik', 'footer.listProperty': 'Daftarkan Properti', 'footer.manageListings': 'Kelola Listing', 'footer.pricing': 'Harga', 'footer.resources': 'Sumber Daya', 'footer.company': 'Perusahaan', 'footer.aboutUs': 'Tentang Kami', 'footer.contact': 'Kontak', 'footer.privacy': 'Kebijakan Privasi', 'footer.terms': 'Syarat Layanan', 'footer.copyright': '© 2025 Baytino. Hak Cipta Dilindungi.',
    'properties.premiumListings': 'Listing Unggulan', 'properties.premiumDesc': 'Pilihan hunian mahasiswa yang dikurasi dengan cermat.', 'properties.featuredBadge': 'Unggulan', 'properties.egpPerMonth': 'EGP/bln', 'properties.noListings': 'Tidak ada listing aktif', 'properties.noListingsDesc': 'Kami sedang memperbarui katalog. Coba lagi nanti!', 'properties.exploreAll': 'Jelajahi Semua Properti',
    'service.plumbing.name': 'Plumbing', 'service.plumbing.desc': 'Tukang ledeng profesional untuk semua kebutuhan air', 'service.electrical.name': 'Listrik', 'service.electrical.desc': 'Teknisi listrik berlisensi untuk pekerjaan yang aman', 'service.cleaning.name': 'Kebersihan', 'service.cleaning.desc': 'Layanan kebersihan profesional untuk rumah dan kantor', 'service.ac.name': 'Servis AC', 'service.ac.desc': 'Ahli perbaikan dan perawatan AC semua merek', 'service.painting.name': 'Pengecatan', 'service.painting.desc': 'Pengecatan profesional interior dan eksterior', 'service.carpentry.name': 'Pertukangan', 'service.carpentry.desc': 'Tukang kayu ahli untuk furnitur dan perbaikan',
    'propertyType.apartment': 'Apartemen', 'propertyType.house': 'Rumah', 'propertyType.villa': 'Vila', 'propertyType.room': 'Kamar', 'propertyType.studio': 'Studio', 'propertyType.property': 'Properti', 'propertyType.roommate': 'Teman Sekamar',
  },
  uz: {
    'nav.home': 'Bosh sahifa', 'nav.properties': 'Mulklar', 'nav.services': 'Xizmatlar', 'nav.login': 'Kirish', 'nav.getStarted': 'Boshlash', 'nav.dashboard': 'Boshqaruv', 'nav.settings': 'Sozlamalar', 'nav.createPost': 'Post yaratish', 'nav.logout': 'Chiqish',
    'hero.title': 'Mukammal Talaba Uyini Toping', 'hero.subtitle': 'Ijara, xonadon va umumiy kvartiralar uchun mulklar qidiring', 'hero.location': 'Manzil', 'hero.propertyType': 'Mulk Turi', 'hero.priceRange': 'Narx Diapazoni', 'hero.search': 'Qidirish', 'hero.apartment': 'Kvartira', 'hero.room': 'Xona', 'hero.roommate': 'Xonadon',
    'stats.properties': 'Mulklar', 'stats.students': 'Talabalar', 'stats.agents': 'Agentlar', 'stats.satisfied': 'Mamnun Mijozlar',
    'properties.featured': 'Ajoyib Mulklar', 'properties.viewAll': 'Barchasini Ko\'rish', 'properties.bedrooms': 'Yotoq Xonalari', 'properties.bathrooms': 'Hammomlar', 'properties.area': 'Maydon', 'properties.month': 'oy',
    'propertiesPage.title': 'Mulklarni Ko\'rish', 'propertiesPage.subtitle': 'Misrda mukammal uyingizni toping', 'propertiesPage.filters': 'Filtrlar', 'propertiesPage.city': 'Manzil', 'propertiesPage.type': 'Turi', 'propertiesPage.price': 'Narx (EGP)', 'propertiesPage.minPrice': 'Min Narx', 'propertiesPage.maxPrice': 'Maks Narx', 'propertiesPage.clearFilters': 'Filtrlarni Tozalash', 'propertiesPage.found': 'Topildi', 'propertiesPage.noProperties': 'Mulk topilmadi', 'propertiesPage.adjustFilters': 'Filtrlarni o\'zgartiring', 'propertiesPage.viewDetails': 'Batafsil', 'propertiesPage.whatsapp': 'WhatsApp', 'propertiesPage.views': 'ko\'rishlar', 'propertiesPage.likes': 'yoqtirishlar',
    'propertiesPage.loading': 'Mulklar yuklanmoqda...', 'propertiesPage.allAreas': 'Barcha hududlar', 'propertiesPage.cairoAll': 'Qohira (Barchasi)', 'propertiesPage.allTypes': 'Barcha turlar', 'propertiesPage.propertyType': 'Mulk', 'propertiesPage.roomType': 'Xona', 'propertiesPage.roommateType': 'Xonadon', 'propertiesPage.any': 'Har qanday', 'propertiesPage.reset': 'Qayta o\'rnatish', 'propertiesPage.apply': 'Qo\'llash', 'propertiesPage.addProperty': 'Mulk qo\'shish', 'propertiesPage.notAvailable': 'Mavjud emas', 'propertiesPage.restore': 'Qayta tiklash', 'propertiesPage.br': 'yotoq', 'propertiesPage.ba': 'hammom', 'propertiesPage.more': 'yana',
    'detail.backToProperties': 'Orqaga', 'detail.home': 'Bosh sahifa', 'detail.properties': 'Mulklar', 'detail.share': 'Ulashish', 'detail.monthlyRent': 'Oylik ijara', 'detail.propertyDetails': 'Mulk tafsilotlari', 'detail.description': 'Tavsif', 'detail.amenities': 'Qulayliklar', 'detail.preferences': 'Afzalliklar', 'detail.videos': 'Mulk videolari', 'detail.postedBy': 'Joylagan', 'detail.yourProperty': 'Sizning mulkingiz', 'detail.manageProperty': 'Ro\'yxatni boshqarish', 'detail.editProperty': 'Mulkni tahrirlash', 'detail.deleteProperty': 'Mulkni o\'chirish', 'detail.deleting': 'O\'chirilmoqda...', 'detail.contactWhatsapp': 'WhatsApp orqali bog\'lanish', 'detail.directMessage': 'Mulk egasiga bevosita xabar', 'detail.safetyTips': 'Xavfsizlik maslahatlari', 'detail.safetyTip1': 'To\'lovdan oldin mulkni shaxsan ko\'ring', 'detail.safetyTip2': 'Mulkni ko\'rmasdan pul o\'tkazmang', 'detail.safetyTip3': 'Mulk egasining shaxsini tekshiring', 'detail.notFound': 'Mulk topilmadi', 'detail.notFoundDesc': 'Bu ro\'yxat o\'chirilgan bo\'lishi mumkin.', 'detail.forFamily': 'Oila uchun', 'detail.forStudents': 'Talabalar uchun', 'detail.furnished': 'Jihozlangan', 'detail.type': 'Turi', 'detail.memberSince': 'A\'zo', 'detail.viewAllPhotos': 'Barcha rasmlarni ko\'rish',
    'services.title': 'Uy Xizmatlari', 'services.viewProviders': 'Provayderlarni Ko\'rish',
    'servicesPage.heroTitle': 'Eshigingiz oldida uy xizmatlari', 'servicesPage.heroSubtitle': 'Qohirada ishonchli mutaxassislarni toping.', 'servicesPage.searchPlaceholder': 'Xizmat qidirish...', 'servicesPage.providers': 'Xizmat ko\'rsatuvchilar', 'servicesPage.categories': 'Kategoriyalar', 'servicesPage.avgRating': 'O\'rtacha reyting', 'servicesPage.availability': 'Mavjudlik', 'servicesPage.ourServices': 'Bizning xizmatlar', 'servicesPage.ourServicesDesc': 'Professional uy xizmatlarimizdan tanlang', 'servicesPage.allServices': 'Barcha xizmatlar', 'servicesPage.noServices': 'Xizmat topilmadi', 'servicesPage.clearSearch': 'Filtrlarni tozalash', 'servicesPage.topProviders': 'Eng yaxshi provayderlar', 'servicesPage.topProvidersDesc': 'Eng yuqori reytingli mutaxassislar', 'servicesPage.verified': 'Tasdiqlangan', 'servicesPage.available': 'Mavjud', 'servicesPage.callNow': 'Qo\'ng\'iroq qiling', 'servicesPage.serviceAreas': 'Xizmat hududlari', 'servicesPage.serviceAreasDesc': 'Qohira bo\'ylab asosiy hududlarni qamrab olamiz', 'servicesPage.howItWorks': 'Qanday ishlaydi', 'servicesPage.howItWorksDesc': '3 oddiy qadamda xizmatni band qiling', 'servicesPage.step1': 'Xizmatni tanlang', 'servicesPage.step1Desc': 'Kategoriyalarni ko\'ring', 'servicesPage.step2': 'Manzilni tanlang', 'servicesPage.step2Desc': 'Yaqin atrofdagi provayderlarni toping', 'servicesPage.step3': 'Bog\'laning', 'servicesPage.step3Desc': 'Bevosita qo\'ng\'iroq qiling', 'servicesPage.needHelp': 'Yordam kerakmi?', 'servicesPage.needHelpDesc': 'Biz bilan bog\'laning.', 'servicesPage.backToHome': 'Bosh sahifaga', 'servicesPage.browseProperties': 'Mulklarni ko\'rish', 'servicesPage.view': 'Ko\'rish', 'servicesPage.providers2': 'provayderlar',
    'post.title': 'Post yaratish', 'post.subtitle': 'Xonadon yoki xona toping', 'post.type': 'Post turi', 'post.property': 'Mulk', 'post.propertyDesc': 'Mulk joylashtirish', 'post.lookingRoommate': 'Xonadon qidirish', 'post.lookingRoommateDesc': 'Birga yashash uchun odam toping', 'post.lookingRoom': 'Xona qidirish', 'post.lookingRoomDesc': 'Yashash joyi toping', 'post.titleLabel': 'Sarlavha', 'post.description': 'Tavsif', 'post.descriptionPlaceholder': 'Mulk yoki talablaringizni tavsiflang...',
    'howItWorks.whyTitle': 'Nega bizni tanlaysiz', 'howItWorks.mainTitle': 'Biz sizning', 'howItWorks.mainTitleHighlight': 'uy qidirish', 'howItWorks.mainTitleEnd': 'tajribangizga g\'amxo\'rlik qilamiz', 'howItWorks.verified': 'Tasdiqlangan mulklar', 'howItWorks.verifiedDesc': 'Barcha mulklar xavfsizligingiz uchun tekshirilgan', 'howItWorks.trusted': 'Ishonchli mulk egalari', 'howItWorks.trustedDesc': 'Tasdiqlangan mulk egalari bilan bog\'laning', 'howItWorks.communication': 'Oson aloqa', 'howItWorks.communicationDesc': 'Bevosita xabar almashish va tez javoblar', 'howItWorks.secure': 'Xavfsiz to\'lov', 'howItWorks.secureDesc': 'Xavfsiz va shaffof ijara shartnomalari', 'howItWorks.title': 'Qanday ishlaydi?', 'howItWorks.subtitle': 'Uyingizni topish uchun 4 oddiy qadamni bajaring.', 'howItWorks.step1': 'Qidirish', 'howItWorks.step1Desc': 'Universitetingiz yaqinida mulk toping.', 'howItWorks.step2': 'Tafsilotlar', 'howItWorks.step2Desc': 'Rasmlar va qulayliklarni tekshiring.', 'howItWorks.step3': 'Aloqa', 'howItWorks.step3Desc': 'Egalar bilan bog\'laning.', 'howItWorks.step4': 'Ko\'chish', 'howItWorks.step4Desc': 'Bandni yakunlang.', 'howItWorks.cta': 'Hozir qidiring',
    'changeLanguage': 'Til', 'common.selectLanguage': 'Til tanlang', 'propertiesPage.search': 'Mulk qidirish...',
    'newProjects.badge': 'Ajoyib to\'plam', 'newProjects.title': 'Ajoyib', 'newProjects.titleHighlight': 'Mulklar', 'newProjects.from': 'dan', 'newProjects.beds': 'yotoq', 'newProjects.noProperties': 'Mulk topilmadi', 'newProjects.noPropertiesDesc': 'Shaharni o\'zgartiring.', 'newProjects.exploreAll': 'Barchasini ko\'ring', 'newProjects.residential': 'Turar joy', 'newProjects.today': 'Bugun',
    'servicesSection.badge': 'Qo\'shimcha qulaylik', 'servicesSection.desc': 'Talabalar hayotini osonlashtiruvchi professional xizmatlar.', 'servicesSection.experts': 'mutaxassis',
    'footer.tagline': 'Misrda talabalar uchun ishonchli platforma', 'footer.forStudents': 'Talabalar uchun', 'footer.findHousing': 'Uy toping', 'footer.findRoommates': 'Xonadon toping', 'footer.postAd': 'E\'lon bering', 'footer.saveProperties': 'Saqlash', 'footer.forOwners': 'Mulk egalari uchun', 'footer.listProperty': 'Mulk joylashtirish', 'footer.manageListings': 'Boshqarish', 'footer.pricing': 'Narxlar', 'footer.resources': 'Resurslar', 'footer.company': 'Kompaniya', 'footer.aboutUs': 'Biz haqimizda', 'footer.contact': 'Aloqa', 'footer.privacy': 'Maxfiylik', 'footer.terms': 'Shartlar', 'footer.copyright': '© 2025 Baytino. Barcha huquqlar himoyalangan.',
    'properties.premiumListings': 'Premium ro\'yxatlar', 'properties.premiumDesc': 'Talabalar uchun mukammal tanlab olingan uy-joy.', 'properties.featuredBadge': 'Tanlangan', 'properties.egpPerMonth': 'EGP/oy', 'properties.noListings': 'Faol ro\'yxat yo\'q', 'properties.noListingsDesc': 'Katalogimizni yangilayapmiz. Keyinroq tekshiring!', 'properties.exploreAll': 'Barcha mulklarni ko\'rish',
    'service.plumbing.name': 'Santexnika', 'service.plumbing.desc': 'Suv va quvurlar uchun professional santexniklar', 'service.electrical.name': 'Elektr', 'service.electrical.desc': 'Xavfsiz elektr ishlari uchun elektriklar', 'service.cleaning.name': 'Tozalash', 'service.cleaning.desc': 'Uy va ofislar uchun professional tozalash', 'service.ac.name': 'Konditsioner ta\'miri', 'service.ac.desc': 'Barcha markali konditsionerlarni ta\'mirlash', 'service.painting.name': 'Bo\'yash', 'service.painting.desc': 'Professional bo\'yash ishlari', 'service.carpentry.name': 'Duradgorlik', 'service.carpentry.desc': 'Mebel va ta\'mirlash uchun duradgorlar',
    'propertyType.apartment': 'Kvartira', 'propertyType.house': 'Uy', 'propertyType.villa': 'Villa', 'propertyType.room': 'Xona', 'propertyType.studio': 'Studiya', 'propertyType.property': 'Mulk', 'propertyType.roommate': 'Xonadon',
  },
  ru: {
    'nav.home': 'Главная', 'nav.properties': 'Недвижимость', 'nav.services': 'Услуги', 'nav.login': 'Войти', 'nav.getStarted': 'Начать', 'nav.dashboard': 'Панель', 'nav.settings': 'Настройки', 'nav.createPost': 'Создать', 'nav.logout': 'Выйти',
    'hero.title': 'Найдите Идеальное Студенческое Жилье', 'hero.subtitle': 'Поиск недвижимости для аренды, соседей и общих квартир', 'hero.location': 'Местоположение', 'hero.propertyType': 'Тип Недвижимости', 'hero.priceRange': 'Ценовой Диапазон', 'hero.search': 'Поиск', 'hero.apartment': 'Квартира', 'hero.room': 'Комната', 'hero.roommate': 'Сосед',
    'stats.properties': 'Объектов', 'stats.students': 'Студентов', 'stats.agents': 'Агентов', 'stats.satisfied': 'Довольных Клиентов',
    'properties.featured': 'Избранные Объекты', 'properties.viewAll': 'Смотреть Все', 'properties.bedrooms': 'Спальни', 'properties.bathrooms': 'Ванные', 'properties.area': 'Площадь', 'properties.month': 'месяц',
    'propertiesPage.title': 'Просмотр Объектов', 'propertiesPage.subtitle': 'Найдите свой идеальный дом в Египте', 'propertiesPage.filters': 'Фильтры', 'propertiesPage.city': 'Расположение', 'propertiesPage.type': 'Тип', 'propertiesPage.price': 'Цена (EGP)', 'propertiesPage.minPrice': 'Мин цена', 'propertiesPage.maxPrice': 'Макс цена', 'propertiesPage.clearFilters': 'Очистить', 'propertiesPage.found': 'Найдено', 'propertiesPage.noProperties': 'Объекты не найдены', 'propertiesPage.adjustFilters': 'Попробуйте изменить фильтры', 'propertiesPage.viewDetails': 'Подробнее', 'propertiesPage.whatsapp': 'WhatsApp', 'propertiesPage.views': 'просмотров', 'propertiesPage.likes': 'лайков',
    'propertiesPage.loading': 'Загрузка...', 'propertiesPage.allAreas': 'Все районы', 'propertiesPage.cairoAll': 'Каир (Все)', 'propertiesPage.allTypes': 'Все типы', 'propertiesPage.propertyType': 'Недвижимость', 'propertiesPage.roomType': 'Комната', 'propertiesPage.roommateType': 'Сосед', 'propertiesPage.any': 'Любой', 'propertiesPage.reset': 'Сброс', 'propertiesPage.apply': 'Применить', 'propertiesPage.addProperty': 'Добавить', 'propertiesPage.notAvailable': 'Недоступно', 'propertiesPage.restore': 'Восстановить', 'propertiesPage.br': 'спал.', 'propertiesPage.ba': 'ванн.', 'propertiesPage.more': 'ещё',
    'detail.backToProperties': 'Назад', 'detail.home': 'Главная', 'detail.properties': 'Недвижимость', 'detail.share': 'Поделиться', 'detail.monthlyRent': 'Месячная аренда', 'detail.propertyDetails': 'Детали объекта', 'detail.description': 'Описание', 'detail.amenities': 'Удобства', 'detail.preferences': 'Предпочтения', 'detail.videos': 'Видео', 'detail.postedBy': 'Размещено', 'detail.yourProperty': 'Ваш объект', 'detail.manageProperty': 'Управление объявлением', 'detail.editProperty': 'Редактировать', 'detail.deleteProperty': 'Удалить', 'detail.deleting': 'Удаление...', 'detail.contactWhatsapp': 'Связаться через WhatsApp', 'detail.directMessage': 'Прямое сообщение владельцу', 'detail.safetyTips': 'Безопасность', 'detail.safetyTip1': 'Посетите объект лично перед оплатой', 'detail.safetyTip2': 'Не переводите деньги без осмотра', 'detail.safetyTip3': 'Проверьте личность владельца', 'detail.notFound': 'Объект не найден', 'detail.notFoundDesc': 'Объявление удалено или недоступно.', 'detail.forFamily': 'Для семьи', 'detail.forStudents': 'Для студентов', 'detail.furnished': 'С мебелью', 'detail.type': 'Тип', 'detail.memberSince': 'Участник с', 'detail.viewAllPhotos': 'Все фото',
    'services.title': 'Домашние Услуги', 'services.viewProviders': 'Поставщики',
    'servicesPage.heroTitle': 'Услуги для дома на пороге', 'servicesPage.heroSubtitle': 'Найдите проверенных специалистов в Каире.', 'servicesPage.searchPlaceholder': 'Поиск услуг...', 'servicesPage.providers': 'Поставщики', 'servicesPage.categories': 'Категории', 'servicesPage.avgRating': 'Средний рейтинг', 'servicesPage.availability': 'Доступность', 'servicesPage.ourServices': 'Наши услуги', 'servicesPage.ourServicesDesc': 'Выберите из наших профессиональных услуг', 'servicesPage.allServices': 'Все услуги', 'servicesPage.noServices': 'Услуги не найдены', 'servicesPage.clearSearch': 'Очистить', 'servicesPage.topProviders': 'Лучшие специалисты', 'servicesPage.topProvidersDesc': 'Отобранные профессионалы', 'servicesPage.verified': 'Проверен', 'servicesPage.available': 'Доступен', 'servicesPage.callNow': 'Позвонить', 'servicesPage.serviceAreas': 'Зоны обслуживания', 'servicesPage.serviceAreasDesc': 'Основные районы Каира', 'servicesPage.howItWorks': 'Как это работает', 'servicesPage.howItWorksDesc': 'Закажите услугу за 3 шага', 'servicesPage.step1': 'Выберите услугу', 'servicesPage.step1Desc': 'Просмотрите категории', 'servicesPage.step2': 'Выберите район', 'servicesPage.step2Desc': 'Найдите ближайших специалистов', 'servicesPage.step3': 'Свяжитесь', 'servicesPage.step3Desc': 'Позвоните или напишите', 'servicesPage.needHelp': 'Нужна помощь?', 'servicesPage.needHelpDesc': 'Свяжитесь с нами.', 'servicesPage.backToHome': 'На главную', 'servicesPage.browseProperties': 'Недвижимость', 'servicesPage.view': 'Смотреть', 'servicesPage.providers2': 'поставщиков',
    'post.title': 'Создать пост', 'post.subtitle': 'Найти соседа или комнату', 'post.type': 'Тип поста', 'post.property': 'Недвижимость', 'post.propertyDesc': 'Разместить объект', 'post.lookingRoommate': 'Ищу соседа', 'post.lookingRoommateDesc': 'Найти кого-то для совместного проживания', 'post.lookingRoom': 'Ищу комнату', 'post.lookingRoomDesc': 'Найти место для проживания', 'post.titleLabel': 'Заголовок', 'post.description': 'Описание', 'post.descriptionPlaceholder': 'Опишите объект или требования...',
    'howItWorks.whyTitle': 'Почему мы', 'howItWorks.mainTitle': 'Мы заботимся о вашем', 'howItWorks.mainTitleHighlight': 'поиске жилья', 'howItWorks.mainTitleEnd': '', 'howItWorks.verified': 'Проверенные объекты', 'howItWorks.verifiedDesc': 'Все объекты проверены для вашей безопасности', 'howItWorks.trusted': 'Надёжные владельцы', 'howItWorks.trustedDesc': 'Связь с проверенными владельцами', 'howItWorks.communication': 'Лёгкое общение', 'howItWorks.communicationDesc': 'Прямые сообщения и быстрые ответы', 'howItWorks.secure': 'Безопасные платежи', 'howItWorks.secureDesc': 'Прозрачные договоры аренды', 'howItWorks.title': 'Как это работает?', 'howItWorks.subtitle': 'Следуйте 4 простым шагам.', 'howItWorks.step1': 'Поиск', 'howItWorks.step1Desc': 'Найдите жильё рядом с университетом.', 'howItWorks.step2': 'Детали', 'howItWorks.step2Desc': 'Проверьте фото и удобства.', 'howItWorks.step3': 'Контакт', 'howItWorks.step3Desc': 'Напишите владельцу.', 'howItWorks.step4': 'Заселение', 'howItWorks.step4Desc': 'Забронируйте и получите ключи.', 'howItWorks.cta': 'Начать поиск',
    'changeLanguage': 'Язык', 'common.selectLanguage': 'Выбрать язык', 'propertiesPage.search': 'Поиск недвижимости...',
    'newProjects.badge': 'Избранная коллекция', 'newProjects.title': 'Избранные', 'newProjects.titleHighlight': 'Объекты', 'newProjects.from': 'от', 'newProjects.beds': 'спален', 'newProjects.noProperties': 'Объекты не найдены', 'newProjects.noPropertiesDesc': 'Попробуйте другой город.', 'newProjects.exploreAll': 'Смотреть все', 'newProjects.residential': 'Жилой', 'newProjects.today': 'Сегодня',
    'servicesSection.badge': 'Дополнительный комфорт', 'servicesSection.desc': 'Профессиональные услуги по обслуживанию для студентов.', 'servicesSection.experts': 'эксперт',
    'footer.tagline': 'Ваша надёжная платформа для студенческого жилья в Египте', 'footer.forStudents': 'Для студентов', 'footer.findHousing': 'Найти жильё', 'footer.findRoommates': 'Найти соседей', 'footer.postAd': 'Подать объявление', 'footer.saveProperties': 'Сохранить', 'footer.forOwners': 'Для владельцев', 'footer.listProperty': 'Разместить объект', 'footer.manageListings': 'Управление', 'footer.pricing': 'Цены', 'footer.resources': 'Ресурсы', 'footer.company': 'Компания', 'footer.aboutUs': 'О нас', 'footer.contact': 'Контакты', 'footer.privacy': 'Конфиденциальность', 'footer.terms': 'Условия', 'footer.copyright': '© 2025 Baytino. Все права защищены.',
    'properties.premiumListings': 'Премиум объявления', 'properties.premiumDesc': 'Тщательно подобранные варианты жилья для студентов.', 'properties.featuredBadge': 'Избранное', 'properties.egpPerMonth': 'EGP/мес', 'properties.noListings': 'Нет активных объявлений', 'properties.noListingsDesc': 'Мы обновляем каталог. Проверьте позже!', 'properties.exploreAll': 'Все объекты',
    'service.plumbing.name': 'Сантехника', 'service.plumbing.desc': 'Профессиональные сантехники', 'service.electrical.name': 'Электрика', 'service.electrical.desc': 'Лицензированные электрики', 'service.cleaning.name': 'Уборка', 'service.cleaning.desc': 'Профессиональная уборка', 'service.ac.name': 'Ремонт кондиционеров', 'service.ac.desc': 'Ремонт и обслуживание кондиционеров', 'service.painting.name': 'Покраска', 'service.painting.desc': 'Профессиональная покраска', 'service.carpentry.name': 'Плотницкие работы', 'service.carpentry.desc': 'Мебель и ремонт',
    'propertyType.apartment': 'Квартира', 'propertyType.house': 'Дом', 'propertyType.villa': 'Вилла', 'propertyType.room': 'Комната', 'propertyType.studio': 'Студия', 'propertyType.property': 'Недвижимость', 'propertyType.roommate': 'Сосед',
  },
  fr: {
    'nav.home': 'Accueil', 'nav.properties': 'Propriétés', 'nav.services': 'Services', 'nav.login': 'Connexion', 'nav.getStarted': 'Commencer', 'nav.dashboard': 'Tableau de bord', 'nav.settings': 'Paramètres', 'nav.createPost': 'Créer', 'nav.logout': 'Déconnexion',
    'hero.title': 'Trouvez Votre Logement Étudiant Parfait', 'hero.subtitle': 'Recherchez des propriétés à louer, des colocataires et des appartements partagés', 'hero.location': 'Emplacement', 'hero.propertyType': 'Type de Propriété', 'hero.priceRange': 'Gamme de Prix', 'hero.search': 'Rechercher', 'hero.apartment': 'Appartement', 'hero.room': 'Chambre', 'hero.roommate': 'Colocataire',
    'stats.properties': 'Propriétés', 'stats.students': 'Étudiants', 'stats.agents': 'Agents', 'stats.satisfied': 'Clients Satisfaits',
    'properties.featured': 'Propriétés en Vedette', 'properties.viewAll': 'Voir Tout', 'properties.bedrooms': 'Chambres', 'properties.bathrooms': 'Salles de Bain', 'properties.area': 'Surface', 'properties.month': 'mois',
    'propertiesPage.title': 'Parcourir les Propriétés', 'propertiesPage.subtitle': 'Trouvez votre maison parfaite en Égypte', 'propertiesPage.filters': 'Filtres', 'propertiesPage.city': 'Emplacement', 'propertiesPage.type': 'Type', 'propertiesPage.price': 'Prix (EGP)', 'propertiesPage.minPrice': 'Prix Min', 'propertiesPage.maxPrice': 'Prix Max', 'propertiesPage.clearFilters': 'Effacer', 'propertiesPage.found': 'Trouvé', 'propertiesPage.noProperties': 'Aucune propriété', 'propertiesPage.adjustFilters': 'Ajustez vos filtres', 'propertiesPage.viewDetails': 'Voir Détails', 'propertiesPage.whatsapp': 'WhatsApp', 'propertiesPage.views': 'vues', 'propertiesPage.likes': 'j\'aime',
    'propertiesPage.loading': 'Chargement...', 'propertiesPage.allAreas': 'Toutes les zones', 'propertiesPage.cairoAll': 'Le Caire (Tout)', 'propertiesPage.allTypes': 'Tous les types', 'propertiesPage.propertyType': 'Propriété', 'propertiesPage.roomType': 'Chambre', 'propertiesPage.roommateType': 'Colocataire', 'propertiesPage.any': 'Tous', 'propertiesPage.reset': 'Réinitialiser', 'propertiesPage.apply': 'Appliquer', 'propertiesPage.addProperty': 'Ajouter', 'propertiesPage.notAvailable': 'Indisponible', 'propertiesPage.restore': 'Restaurer', 'propertiesPage.br': 'ch.', 'propertiesPage.ba': 'sdb', 'propertiesPage.more': 'plus',
    'detail.backToProperties': 'Retour', 'detail.home': 'Accueil', 'detail.properties': 'Propriétés', 'detail.share': 'Partager', 'detail.monthlyRent': 'Loyer mensuel', 'detail.propertyDetails': 'Détails', 'detail.description': 'Description', 'detail.amenities': 'Équipements', 'detail.preferences': 'Préférences', 'detail.videos': 'Vidéos', 'detail.postedBy': 'Publié par', 'detail.yourProperty': 'Votre propriété', 'detail.manageProperty': 'Gérer votre annonce', 'detail.editProperty': 'Modifier', 'detail.deleteProperty': 'Supprimer', 'detail.deleting': 'Suppression...', 'detail.contactWhatsapp': 'Contacter via WhatsApp', 'detail.directMessage': 'Message direct au propriétaire', 'detail.safetyTips': 'Sécurité', 'detail.safetyTip1': 'Visitez toujours le bien avant de payer', 'detail.safetyTip2': 'Ne transférez jamais d\'argent sans visite', 'detail.safetyTip3': 'Vérifiez l\'identité du propriétaire', 'detail.notFound': 'Propriété introuvable', 'detail.notFoundDesc': 'Cette annonce a été supprimée.', 'detail.forFamily': 'Pour famille', 'detail.forStudents': 'Pour étudiants', 'detail.furnished': 'Meublé', 'detail.type': 'Type', 'detail.memberSince': 'Membre depuis', 'detail.viewAllPhotos': 'Voir toutes les photos',
    'services.title': 'Services à Domicile', 'services.viewProviders': 'Voir Fournisseurs',
    'servicesPage.heroTitle': 'Services à votre porte', 'servicesPage.heroSubtitle': 'Trouvez des professionnels de confiance au Caire.', 'servicesPage.searchPlaceholder': 'Rechercher un service...', 'servicesPage.providers': 'Prestataires', 'servicesPage.categories': 'Catégories', 'servicesPage.avgRating': 'Note moyenne', 'servicesPage.availability': 'Disponibilité', 'servicesPage.ourServices': 'Nos services', 'servicesPage.ourServicesDesc': 'Choisissez parmi nos services professionnels', 'servicesPage.allServices': 'Tous les services', 'servicesPage.noServices': 'Aucun service trouvé', 'servicesPage.clearSearch': 'Effacer', 'servicesPage.topProviders': 'Meilleurs prestataires', 'servicesPage.topProvidersDesc': 'Professionnels les mieux notés', 'servicesPage.verified': 'Vérifié', 'servicesPage.available': 'Disponible', 'servicesPage.callNow': 'Appeler', 'servicesPage.serviceAreas': 'Zones de service', 'servicesPage.serviceAreasDesc': 'Zones principales du Caire', 'servicesPage.howItWorks': 'Comment ça marche', 'servicesPage.howItWorksDesc': 'Réservez en 3 étapes', 'servicesPage.step1': 'Choisir le service', 'servicesPage.step1Desc': 'Parcourez les catégories', 'servicesPage.step2': 'Choisir le lieu', 'servicesPage.step2Desc': 'Trouvez des prestataires proches', 'servicesPage.step3': 'Contacter', 'servicesPage.step3Desc': 'Appelez directement', 'servicesPage.needHelp': 'Besoin d\'aide?', 'servicesPage.needHelpDesc': 'Contactez-nous.', 'servicesPage.backToHome': 'Accueil', 'servicesPage.browseProperties': 'Propriétés', 'servicesPage.view': 'Voir', 'servicesPage.providers2': 'prestataires',
    'post.title': 'Créer une annonce', 'post.subtitle': 'Trouver un colocataire ou une chambre', 'post.type': 'Type d\'annonce', 'post.property': 'Propriété', 'post.propertyDesc': 'Lister une propriété', 'post.lookingRoommate': 'Cherche colocataire', 'post.lookingRoommateDesc': 'Trouver quelqu\'un pour partager', 'post.lookingRoom': 'Cherche chambre', 'post.lookingRoomDesc': 'Trouver un logement', 'post.titleLabel': 'Titre', 'post.description': 'Description', 'post.descriptionPlaceholder': 'Décrivez votre propriété...',
    'howItWorks.whyTitle': 'Pourquoi nous choisir', 'howItWorks.mainTitle': 'Nous nous soucions de votre', 'howItWorks.mainTitleHighlight': 'recherche de logement', 'howItWorks.mainTitleEnd': '', 'howItWorks.verified': 'Propriétés vérifiées', 'howItWorks.verifiedDesc': 'Tous les biens sont vérifiés', 'howItWorks.trusted': 'Propriétaires fiables', 'howItWorks.trustedDesc': 'Propriétaires vérifiés et de confiance', 'howItWorks.communication': 'Communication facile', 'howItWorks.communicationDesc': 'Messagerie directe et réponses rapides', 'howItWorks.secure': 'Paiements sécurisés', 'howItWorks.secureDesc': 'Contrats transparents et sûrs', 'howItWorks.title': 'Comment ça marche?', 'howItWorks.subtitle': 'Suivez ces 4 étapes simples.', 'howItWorks.step1': 'Chercher', 'howItWorks.step1Desc': 'Trouvez un bien près de votre université.', 'howItWorks.step2': 'Détails', 'howItWorks.step2Desc': 'Consultez photos et équipements.', 'howItWorks.step3': 'Contact', 'howItWorks.step3Desc': 'Contactez les propriétaires.', 'howItWorks.step4': 'Emménager', 'howItWorks.step4Desc': 'Finalisez la réservation.', 'howItWorks.cta': 'Commencer la recherche',
    'changeLanguage': 'Langue', 'common.selectLanguage': 'Choisir la langue', 'propertiesPage.search': 'Rechercher propriétés...',
    'newProjects.badge': 'Collection vedette', 'newProjects.title': 'Propriétés', 'newProjects.titleHighlight': 'vedettes', 'newProjects.from': 'à partir de', 'newProjects.beds': 'chambres', 'newProjects.noProperties': 'Aucune propriété', 'newProjects.noPropertiesDesc': 'Essayez une autre ville.', 'newProjects.exploreAll': 'Voir tout', 'newProjects.residential': 'Résidentiel', 'newProjects.today': 'Aujourd\'hui',
    'servicesSection.badge': 'Confort supplémentaire', 'servicesSection.desc': 'Services de maintenance professionnels pour faciliter votre vie étudiante.', 'servicesSection.experts': 'experts',
    'footer.tagline': 'Votre plateforme de confiance pour le logement étudiant en Égypte', 'footer.forStudents': 'Pour les étudiants', 'footer.findHousing': 'Trouver un logement', 'footer.findRoommates': 'Trouver des colocataires', 'footer.postAd': 'Publier une annonce', 'footer.saveProperties': 'Sauvegarder', 'footer.forOwners': 'Pour les propriétaires', 'footer.listProperty': 'Lister un bien', 'footer.manageListings': 'Gérer', 'footer.pricing': 'Tarifs', 'footer.resources': 'Ressources', 'footer.company': 'Société', 'footer.aboutUs': 'À propos', 'footer.contact': 'Contact', 'footer.privacy': 'Confidentialité', 'footer.terms': 'Conditions', 'footer.copyright': '© 2025 Baytino. Tous droits réservés.',
    'properties.premiumListings': 'Annonces premium', 'properties.premiumDesc': 'Logements étudiants soigneusement sélectionnés.', 'properties.featuredBadge': 'Vedette', 'properties.egpPerMonth': 'EGP/mois', 'properties.noListings': 'Aucune annonce active', 'properties.noListingsDesc': 'Nous mettons à jour notre catalogue. Revenez plus tard!', 'properties.exploreAll': 'Explorer toutes les propriétés',
    'service.plumbing.name': 'Plomberie', 'service.plumbing.desc': 'Plombiers professionnels', 'service.electrical.name': 'Électricité', 'service.electrical.desc': 'Électriciens agréés', 'service.cleaning.name': 'Nettoyage', 'service.cleaning.desc': 'Services de nettoyage professionnels', 'service.ac.name': 'Climatisation', 'service.ac.desc': 'Réparation et entretien de climatiseurs', 'service.painting.name': 'Peinture', 'service.painting.desc': 'Peintres professionnels', 'service.carpentry.name': 'Menuiserie', 'service.carpentry.desc': 'Menuisiers qualifiés',
    'propertyType.apartment': 'Appartement', 'propertyType.house': 'Maison', 'propertyType.villa': 'Villa', 'propertyType.room': 'Chambre', 'propertyType.studio': 'Studio', 'propertyType.property': 'Propriété', 'propertyType.roommate': 'Colocataire',
  },
  kk: {
    'nav.home': 'Басты бет', 'nav.properties': 'Мүлік', 'nav.services': 'Қызметтер', 'nav.login': 'Кіру', 'nav.getStarted': 'Бастау', 'nav.dashboard': 'Басқару', 'nav.settings': 'Параметрлер', 'nav.createPost': 'Жасау', 'nav.logout': 'Шығу',
    'hero.title': 'Студенттік Үйіңізді Табыңыз', 'hero.subtitle': 'Жалға алу, бөлмелес және ортақ пәтерлерді іздеңіз', 'hero.location': 'Орны', 'hero.propertyType': 'Мүлік Түрі', 'hero.priceRange': 'Баға Диапазоны', 'hero.search': 'Іздеу', 'hero.apartment': 'Пәтер', 'hero.room': 'Бөлме', 'hero.roommate': 'Бөлмелес',
    'stats.properties': 'Мүлік', 'stats.students': 'Студенттер', 'stats.agents': 'Агенттер', 'stats.satisfied': 'Қанағаттанған Клиенттер',
    'properties.featured': 'Таңдаулы Мүлік', 'properties.viewAll': 'Барлығын Көру', 'properties.bedrooms': 'Жатын Бөлмелер', 'properties.bathrooms': 'Жуынатын Бөлмелер', 'properties.area': 'Аумақ', 'properties.month': 'ай',
    'propertiesPage.title': 'Мүлікті Шолу', 'propertiesPage.subtitle': 'Мысырда өзіңіздің үйіңізді табыңыз', 'propertiesPage.filters': 'Сүзгілер', 'propertiesPage.city': 'Орны', 'propertiesPage.type': 'Түрі', 'propertiesPage.price': 'Баға (EGP)', 'propertiesPage.minPrice': 'Мин баға', 'propertiesPage.maxPrice': 'Макс баға', 'propertiesPage.clearFilters': 'Тазалау', 'propertiesPage.found': 'Табылды', 'propertiesPage.noProperties': 'Мүлік табылмады', 'propertiesPage.adjustFilters': 'Сүзгілерді өзгертіңіз', 'propertiesPage.viewDetails': 'Толығырақ', 'propertiesPage.whatsapp': 'WhatsApp', 'propertiesPage.views': 'көрулер', 'propertiesPage.likes': 'ұнатулар',
    'propertiesPage.loading': 'Жүктелуде...', 'propertiesPage.allAreas': 'Барлық аймақтар', 'propertiesPage.cairoAll': 'Каир (Барлығы)', 'propertiesPage.allTypes': 'Барлық түрлер', 'propertiesPage.propertyType': 'Мүлік', 'propertiesPage.roomType': 'Бөлме', 'propertiesPage.roommateType': 'Бөлмелес', 'propertiesPage.any': 'Кез келген', 'propertiesPage.reset': 'Қалпына келтіру', 'propertiesPage.apply': 'Қолдану', 'propertiesPage.addProperty': 'Мүлік қосу', 'propertiesPage.notAvailable': 'Жоқ', 'propertiesPage.restore': 'Қалпына келтіру', 'propertiesPage.br': 'жатын', 'propertiesPage.ba': 'ванна', 'propertiesPage.more': 'тағы',
    'detail.backToProperties': 'Артқа', 'detail.home': 'Басты бет', 'detail.properties': 'Мүлік', 'detail.share': 'Бөлісу', 'detail.monthlyRent': 'Айлық жалдау', 'detail.propertyDetails': 'Мүлік мәліметтері', 'detail.description': 'Сипаттама', 'detail.amenities': 'Ыңғайлылықтар', 'detail.preferences': 'Қалаулар', 'detail.videos': 'Бейнелер', 'detail.postedBy': 'Жариялаған', 'detail.yourProperty': 'Сіздің мүлік', 'detail.manageProperty': 'Жарнаманы басқару', 'detail.editProperty': 'Өңдеу', 'detail.deleteProperty': 'Жою', 'detail.deleting': 'Жойылуда...', 'detail.contactWhatsapp': 'WhatsApp арқылы байланысу', 'detail.directMessage': 'Мүлік иесіне тікелей хабарлама', 'detail.safetyTips': 'Қауіпсіздік', 'detail.safetyTip1': 'Төлемнен бұрын мүлікті жеке көріңіз', 'detail.safetyTip2': 'Көрмей ақша аудармаңыз', 'detail.safetyTip3': 'Мүлік иесін тексеріңіз', 'detail.notFound': 'Мүлік табылмады', 'detail.notFoundDesc': 'Бұл жарнама жойылған болуы мүмкін.', 'detail.forFamily': 'Отбасы үшін', 'detail.forStudents': 'Студенттер үшін', 'detail.furnished': 'Жиһазды', 'detail.type': 'Түрі', 'detail.memberSince': 'Мүше', 'detail.viewAllPhotos': 'Барлық суреттер',
    'services.title': 'Үй Қызметтері', 'services.viewProviders': 'Жабдықтаушылар',
    'servicesPage.heroTitle': 'Есігіңізде үй қызметтері', 'servicesPage.heroSubtitle': 'Каирде сенімді мамандарды табыңыз.', 'servicesPage.searchPlaceholder': 'Қызмет іздеу...', 'servicesPage.providers': 'Жабдықтаушылар', 'servicesPage.categories': 'Санаттар', 'servicesPage.avgRating': 'Орташа рейтинг', 'servicesPage.availability': 'Қолжетімділік', 'servicesPage.ourServices': 'Біздің қызметтер', 'servicesPage.ourServicesDesc': 'Кәсіби қызметтерімізден таңдаңыз', 'servicesPage.allServices': 'Барлық қызметтер', 'servicesPage.noServices': 'Қызмет табылмады', 'servicesPage.clearSearch': 'Тазалау', 'servicesPage.topProviders': 'Үздік мамандар', 'servicesPage.topProvidersDesc': 'Ең жоғары рейтингті мамандар', 'servicesPage.verified': 'Тексерілген', 'servicesPage.available': 'Қолжетімді', 'servicesPage.callNow': 'Қоңырау шалу', 'servicesPage.serviceAreas': 'Қызмет аймақтары', 'servicesPage.serviceAreasDesc': 'Каирдің негізгі аймақтары', 'servicesPage.howItWorks': 'Қалай жұмыс істейді', 'servicesPage.howItWorksDesc': '3 қадамда тапсырыс беріңіз', 'servicesPage.step1': 'Қызметті таңдаңыз', 'servicesPage.step1Desc': 'Санаттарды шолыңыз', 'servicesPage.step2': 'Орынды таңдаңыз', 'servicesPage.step2Desc': 'Жақын мамандарды табыңыз', 'servicesPage.step3': 'Байланысыңыз', 'servicesPage.step3Desc': 'Тікелей қоңырау шалыңыз', 'servicesPage.needHelp': 'Көмек керек пе?', 'servicesPage.needHelpDesc': 'Бізбен байланысыңыз.', 'servicesPage.backToHome': 'Басты бетке', 'servicesPage.browseProperties': 'Мүлікті шолу', 'servicesPage.view': 'Көру', 'servicesPage.providers2': 'маман',
    'post.title': 'Пост жасау', 'post.subtitle': 'Бөлмелес немесе бөлме табу', 'post.type': 'Пост түрі', 'post.property': 'Мүлік', 'post.propertyDesc': 'Мүлік орналастыру', 'post.lookingRoommate': 'Бөлмелес іздеу', 'post.lookingRoommateDesc': 'Бірге тұру үшін адам табу', 'post.lookingRoom': 'Бөлме іздеу', 'post.lookingRoomDesc': 'Тұратын жер табу', 'post.titleLabel': 'Тақырыбы', 'post.description': 'Сипаттама', 'post.descriptionPlaceholder': 'Мүлікті немесе талаптарыңызды сипаттаңыз...',
    'howItWorks.whyTitle': 'Неге бізді таңдайсыз', 'howItWorks.mainTitle': 'Біз сіздің', 'howItWorks.mainTitleHighlight': 'үй іздеу', 'howItWorks.mainTitleEnd': 'тәжірибеңізге қамқорлық жасаймыз', 'howItWorks.verified': 'Тексерілген мүлік', 'howItWorks.verifiedDesc': 'Барлық мүлік қауіпсіздік үшін тексерілген', 'howItWorks.trusted': 'Сенімді иелер', 'howItWorks.trustedDesc': 'Тексерілген мүлік иелерімен байланысыңыз', 'howItWorks.communication': 'Оңай байланыс', 'howItWorks.communicationDesc': 'Тікелей хабарлама және жылдам жауаптар', 'howItWorks.secure': 'Қауіпсіз төлемдер', 'howItWorks.secureDesc': 'Қауіпсіз және ашық жалдау келісімдері', 'howItWorks.title': 'Қалай жұмыс істейді?', 'howItWorks.subtitle': '4 қарапайым қадамды орындаңыз.', 'howItWorks.step1': 'Іздеу', 'howItWorks.step1Desc': 'Университетіңізге жақын мүлік табыңыз.', 'howItWorks.step2': 'Мәліметтер', 'howItWorks.step2Desc': 'Суреттер мен ыңғайлылықтарды тексеріңіз.', 'howItWorks.step3': 'Байланыс', 'howItWorks.step3Desc': 'Иелерге хабарласыңыз.', 'howItWorks.step4': 'Көшу', 'howItWorks.step4Desc': 'Брондауды аяқтаңыз.', 'howItWorks.cta': 'Қазір іздеу',
    'changeLanguage': 'Тіл', 'common.selectLanguage': 'Тіл таңдау', 'propertiesPage.search': 'Мүлік іздеу...',
    'newProjects.badge': 'Таңдаулы жинақ', 'newProjects.title': 'Таңдаулы', 'newProjects.titleHighlight': 'Мүліктер', 'newProjects.from': 'бастап', 'newProjects.beds': 'жатын', 'newProjects.noProperties': 'Мүлік табылмады', 'newProjects.noPropertiesDesc': 'Қаланы өзгертіп көріңіз.', 'newProjects.exploreAll': 'Бәрін көру', 'newProjects.residential': 'Тұрғын', 'newProjects.today': 'Бүгін',
    'servicesSection.badge': 'Қосымша жайлылық', 'servicesSection.desc': 'Студент өміріңізді жеңілдетуге арналған кәсіби қызметтер.', 'servicesSection.experts': 'маман',
    'footer.tagline': 'Мысырда студенттік тұрғын үй үшін сенімді платформа', 'footer.forStudents': 'Студенттер үшін', 'footer.findHousing': 'Тұрғын үй табу', 'footer.findRoommates': 'Бөлмелес табу', 'footer.postAd': 'Хабарландыру беру', 'footer.saveProperties': 'Сақтау', 'footer.forOwners': 'Иелер үшін', 'footer.listProperty': 'Мүлік орналастыру', 'footer.manageListings': 'Басқару', 'footer.pricing': 'Бағалар', 'footer.resources': 'Ресурстар', 'footer.company': 'Компания', 'footer.aboutUs': 'Біз туралы', 'footer.contact': 'Байланыс', 'footer.privacy': 'Құпиялылық', 'footer.terms': 'Шарттар', 'footer.copyright': '© 2025 Baytino. Барлық құқықтар қорғалған.',
    'properties.premiumListings': 'Премиум хабарламалар', 'properties.premiumDesc': 'Студенттерге арналған мұқият іріктелген тұрғын үй.', 'properties.featuredBadge': 'Таңдаулы', 'properties.egpPerMonth': 'EGP/ай', 'properties.noListings': 'Белсенді хабарлама жоқ', 'properties.noListingsDesc': 'Каталогты жаңартып жатырмыз. Кейінірек тексеріңіз!', 'properties.exploreAll': 'Барлық мүлікті қарау',
    'service.plumbing.name': 'Сантехника', 'service.plumbing.desc': 'Кәсіби сантехниктер', 'service.electrical.name': 'Электрика', 'service.electrical.desc': 'Лицензиялы электриктер', 'service.cleaning.name': 'Тазалау', 'service.cleaning.desc': 'Кәсіби тазалау қызметтері', 'service.ac.name': 'Кондиционер жөндеу', 'service.ac.desc': 'Кондиционерлерді жөндеу', 'service.painting.name': 'Бояу', 'service.painting.desc': 'Кәсіби бояу жұмыстары', 'service.carpentry.name': 'Ұсталық', 'service.carpentry.desc': 'Жиһаз жасау және жөндеу',
    'propertyType.apartment': 'Пәтер', 'propertyType.house': 'Үй', 'propertyType.villa': 'Вилла', 'propertyType.room': 'Бөлме', 'propertyType.studio': 'Студия', 'propertyType.property': 'Мүлік', 'propertyType.roommate': 'Бөлмелес',
  },
  ms: {
    'nav.home': 'Utama', 'nav.properties': 'Hartanah', 'nav.services': 'Perkhidmatan', 'nav.login': 'Log Masuk', 'nav.getStarted': 'Mula', 'nav.dashboard': 'Papan Pemuka', 'nav.settings': 'Tetapan', 'nav.createPost': 'Buat', 'nav.logout': 'Log Keluar',
    'hero.title': 'Cari Perumahan Pelajar Sempurna Anda', 'hero.subtitle': 'Cari hartanah untuk disewa, rakan sebilik, dan pangsapuri berkongsi', 'hero.location': 'Lokasi', 'hero.propertyType': 'Jenis Hartanah', 'hero.priceRange': 'Julat Harga', 'hero.search': 'Cari', 'hero.apartment': 'Pangsapuri', 'hero.room': 'Bilik', 'hero.roommate': 'Rakan Sebilik',
    'stats.properties': 'Hartanah', 'stats.students': 'Pelajar', 'stats.agents': 'Ejen', 'stats.satisfied': 'Pelanggan Berpuas Hati',
    'properties.featured': 'Hartanah Pilihan', 'properties.viewAll': 'Lihat Semua', 'properties.bedrooms': 'Bilik Tidur', 'properties.bathrooms': 'Bilik Mandi', 'properties.area': 'Kawasan', 'properties.month': 'bulan',
    'propertiesPage.title': 'Semak Hartanah', 'propertiesPage.subtitle': 'Cari rumah sempurna anda di Mesir', 'propertiesPage.filters': 'Penapis', 'propertiesPage.city': 'Lokasi', 'propertiesPage.type': 'Jenis', 'propertiesPage.price': 'Harga (EGP)', 'propertiesPage.minPrice': 'Harga Min', 'propertiesPage.maxPrice': 'Harga Maks', 'propertiesPage.clearFilters': 'Kosongkan', 'propertiesPage.found': 'Dijumpai', 'propertiesPage.noProperties': 'Tiada hartanah', 'propertiesPage.adjustFilters': 'Cuba laraskan penapis', 'propertiesPage.viewDetails': 'Lihat Butiran', 'propertiesPage.whatsapp': 'WhatsApp', 'propertiesPage.views': 'tontonan', 'propertiesPage.likes': 'suka',
    'propertiesPage.loading': 'Memuatkan...', 'propertiesPage.allAreas': 'Semua kawasan', 'propertiesPage.cairoAll': 'Kaherah (Semua)', 'propertiesPage.allTypes': 'Semua jenis', 'propertiesPage.propertyType': 'Hartanah', 'propertiesPage.roomType': 'Bilik', 'propertiesPage.roommateType': 'Rakan Sebilik', 'propertiesPage.any': 'Mana-mana', 'propertiesPage.reset': 'Set semula', 'propertiesPage.apply': 'Guna', 'propertiesPage.addProperty': 'Tambah', 'propertiesPage.notAvailable': 'Tidak tersedia', 'propertiesPage.restore': 'Pulihkan', 'propertiesPage.br': 'BT', 'propertiesPage.ba': 'BM', 'propertiesPage.more': 'lagi',
    'detail.backToProperties': 'Kembali', 'detail.home': 'Utama', 'detail.properties': 'Hartanah', 'detail.share': 'Kongsi', 'detail.monthlyRent': 'Sewa bulanan', 'detail.propertyDetails': 'Butiran hartanah', 'detail.description': 'Penerangan', 'detail.amenities': 'Kemudahan', 'detail.preferences': 'Keutamaan', 'detail.videos': 'Video', 'detail.postedBy': 'Disiarkan oleh', 'detail.yourProperty': 'Hartanah anda', 'detail.manageProperty': 'Urus senarai anda', 'detail.editProperty': 'Edit', 'detail.deleteProperty': 'Padam', 'detail.deleting': 'Memadam...', 'detail.contactWhatsapp': 'Hubungi melalui WhatsApp', 'detail.directMessage': 'Mesej terus kepada pemilik', 'detail.safetyTips': 'Tips keselamatan', 'detail.safetyTip1': 'Lawat hartanah secara peribadi sebelum membayar', 'detail.safetyTip2': 'Jangan pindah wang tanpa melihat hartanah', 'detail.safetyTip3': 'Sahkan identiti pemilik', 'detail.notFound': 'Hartanah tidak dijumpai', 'detail.notFoundDesc': 'Senarai ini mungkin telah dipadamkan.', 'detail.forFamily': 'Untuk keluarga', 'detail.forStudents': 'Untuk pelajar', 'detail.furnished': 'Berperabot', 'detail.type': 'Jenis', 'detail.memberSince': 'Ahli sejak', 'detail.viewAllPhotos': 'Lihat semua foto',
    'services.title': 'Perkhidmatan Rumah', 'services.viewProviders': 'Lihat Pembekal',
    'servicesPage.heroTitle': 'Perkhidmatan rumah di depan pintu anda', 'servicesPage.heroSubtitle': 'Cari profesional dipercayai di Kaherah.', 'servicesPage.searchPlaceholder': 'Cari perkhidmatan...', 'servicesPage.providers': 'Pembekal', 'servicesPage.categories': 'Kategori', 'servicesPage.avgRating': 'Penilaian purata', 'servicesPage.availability': 'Ketersediaan', 'servicesPage.ourServices': 'Perkhidmatan kami', 'servicesPage.ourServicesDesc': 'Pilih dari perkhidmatan profesional kami', 'servicesPage.allServices': 'Semua perkhidmatan', 'servicesPage.noServices': 'Tiada perkhidmatan', 'servicesPage.clearSearch': 'Kosongkan', 'servicesPage.topProviders': 'Pembekal teratas', 'servicesPage.topProvidersDesc': 'Profesional pilihan', 'servicesPage.verified': 'Disahkan', 'servicesPage.available': 'Tersedia', 'servicesPage.callNow': 'Hubungi', 'servicesPage.serviceAreas': 'Kawasan perkhidmatan', 'servicesPage.serviceAreasDesc': 'Kawasan utama di Kaherah', 'servicesPage.howItWorks': 'Cara ia berfungsi', 'servicesPage.howItWorksDesc': 'Tempah dalam 3 langkah', 'servicesPage.step1': 'Pilih perkhidmatan', 'servicesPage.step1Desc': 'Layari kategori', 'servicesPage.step2': 'Pilih lokasi', 'servicesPage.step2Desc': 'Cari pembekal berdekatan', 'servicesPage.step3': 'Hubungi', 'servicesPage.step3Desc': 'Hubungi terus', 'servicesPage.needHelp': 'Perlukan bantuan?', 'servicesPage.needHelpDesc': 'Hubungi kami.', 'servicesPage.backToHome': 'Kembali', 'servicesPage.browseProperties': 'Lihat hartanah', 'servicesPage.view': 'Lihat', 'servicesPage.providers2': 'pembekal',
    'post.title': 'Buat siaran', 'post.subtitle': 'Cari rakan sebilik atau bilik', 'post.type': 'Jenis siaran', 'post.property': 'Hartanah', 'post.propertyDesc': 'Senaraikan hartanah', 'post.lookingRoommate': 'Cari rakan sebilik', 'post.lookingRoommateDesc': 'Cari orang untuk berkongsi', 'post.lookingRoom': 'Cari bilik', 'post.lookingRoomDesc': 'Cari tempat tinggal', 'post.titleLabel': 'Tajuk', 'post.description': 'Penerangan', 'post.descriptionPlaceholder': 'Huraikan hartanah atau keperluan anda...',
    'howItWorks.whyTitle': 'Mengapa pilih kami', 'howItWorks.mainTitle': 'Kami mengambil berat tentang', 'howItWorks.mainTitleHighlight': 'carian rumah', 'howItWorks.mainTitleEnd': 'anda', 'howItWorks.verified': 'Hartanah disahkan', 'howItWorks.verifiedDesc': 'Semua hartanah disahkan untuk keselamatan', 'howItWorks.trusted': 'Pemilik dipercayai', 'howItWorks.trustedDesc': 'Berhubung dengan pemilik yang disahkan', 'howItWorks.communication': 'Komunikasi mudah', 'howItWorks.communicationDesc': 'Mesej terus dan respons pantas', 'howItWorks.secure': 'Bayaran selamat', 'howItWorks.secureDesc': 'Perjanjian sewa yang selamat dan telus', 'howItWorks.title': 'Bagaimana ia berfungsi?', 'howItWorks.subtitle': 'Ikuti 4 langkah mudah ini.', 'howItWorks.step1': 'Cari', 'howItWorks.step1Desc': 'Cari hartanah berdekatan universiti.', 'howItWorks.step2': 'Butiran', 'howItWorks.step2Desc': 'Semak foto dan kemudahan.', 'howItWorks.step3': 'Hubungi', 'howItWorks.step3Desc': 'Mesej pemilik dan jadualkan lawatan.', 'howItWorks.step4': 'Pindah masuk', 'howItWorks.step4Desc': 'Lengkapkan tempahan.', 'howItWorks.cta': 'Mula mencari sekarang',
    'changeLanguage': 'Bahasa', 'common.selectLanguage': 'Pilih Bahasa', 'propertiesPage.search': 'Cari hartanah...',
    'newProjects.badge': 'Koleksi Pilihan', 'newProjects.title': 'Hartanah', 'newProjects.titleHighlight': 'Pilihan', 'newProjects.from': 'dari', 'newProjects.beds': 'Bilik', 'newProjects.noProperties': 'Tiada hartanah', 'newProjects.noPropertiesDesc': 'Cuba tukar bandar.', 'newProjects.exploreAll': 'Terokai Semua', 'newProjects.residential': 'Kediaman', 'newProjects.today': 'Hari ini',
    'servicesSection.badge': 'Keselesaan Tambahan', 'servicesSection.desc': 'Perkhidmatan penyelenggaraan profesional untuk kehidupan pelajar anda.', 'servicesSection.experts': 'pakar',
    'footer.tagline': 'Platform terpercaya anda untuk perumahan pelajar di Mesir', 'footer.forStudents': 'Untuk Pelajar', 'footer.findHousing': 'Cari Perumahan', 'footer.findRoommates': 'Cari Rakan Sebilik', 'footer.postAd': 'Pasang Iklan', 'footer.saveProperties': 'Simpan', 'footer.forOwners': 'Untuk Pemilik', 'footer.listProperty': 'Senaraikan', 'footer.manageListings': 'Urus', 'footer.pricing': 'Harga', 'footer.resources': 'Sumber', 'footer.company': 'Syarikat', 'footer.aboutUs': 'Tentang Kami', 'footer.contact': 'Hubungi', 'footer.privacy': 'Privasi', 'footer.terms': 'Terma', 'footer.copyright': '© 2025 Baytino. Hak Cipta Terpelihara.',
    'properties.premiumListings': 'Senarai Premium', 'properties.premiumDesc': 'Pilihan perumahan pelajar yang dikurasi dengan teliti untuk keselesaan dan kejayaan.', 'properties.featuredBadge': 'Pilihan', 'properties.egpPerMonth': 'EGP/bln', 'properties.noListings': 'Tiada senarai aktif', 'properties.noListingsDesc': 'Kami sedang mengemas kini katalog kami. Sila semak semula dalam beberapa jam!', 'properties.exploreAll': 'Terokai Semua Hartanah',
    'service.plumbing.name': 'Paip', 'service.plumbing.desc': 'Pakar paip profesional untuk semua keperluan air dan paip anda', 'service.electrical.name': 'Elektrik', 'service.electrical.desc': 'Juruletrik berlesen untuk kerja elektrik yang selamat', 'service.cleaning.name': 'Pembersihan', 'service.cleaning.desc': 'Perkhidmatan pembersihan profesional untuk rumah dan pejabat', 'service.ac.name': 'Servis AC', 'service.ac.desc': 'Pakar pembaikan dan penyelenggaraan AC untuk semua jenama', 'service.painting.name': 'Pengecatan', 'service.painting.desc': 'Pelukis profesional untuk kerja dalaman dan luaran', 'service.carpentry.name': 'Pertukangan', 'service.carpentry.desc': 'Tukang kayu mahir untuk perabot kustom dan pembaikan',
    'propertyType.apartment': 'Pangsapuri', 'propertyType.house': 'Rumah', 'propertyType.villa': 'Vila', 'propertyType.room': 'Bilik', 'propertyType.studio': 'Studio', 'propertyType.property': 'Hartanah', 'propertyType.roommate': 'Rakan Sebilik',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    if (saved) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
